### ISSUE TITLE
TruLens with Outside Logs example not working

### ISSUE THREAD

**Issue by atulm-encora** [truera/trulens#1005]
**Bug Description**
I copied the example given at https://github.com/truera/trulens/blob/main/trulens_eval/examples/quickstart/existing_data_quickstart.ipynb. After running the example the dashboard is not showing any data for feedback. I ran this on Ubuntu 22 machine.

**To Reproduce**
Copy code from above link and run it

**Expected behavior**
It should show the scores for Answer relevance and Groundedness feedback functions.

**Relevant Logs/Tracebacks**
Using legacy llama_index version None. Consider upgrading to 0.10.0 or later.
✅ In qs_relevance, input question will be set to __record__.main_input or `Select.RecordInput` .
✅ In qs_relevance, input statement will be set to __record__.app.retriever.get_context.rets[:] .
✅ In Groundedness, input source will be set to __record__.app.retriever.get_context.rets[:].collect() .
✅ In Groundedness, input statement will be set to __record__.main_output or `Select.RecordOutput` .
✅ In Answer Relevance, input prompt will be set to __record__.main_input or `Select.RecordInput` .
✅ In Answer Relevance, input response will be set to __record__.main_output or `Select.RecordOutput` .
🦑 Tru initialized with db url sqlite:///default.sqlite .
🛑 Secret keys may be written to the database. See the `database_redact_keys` option of Tru` to prevent this.
Force stopping dashboard ...
Starting dashboard ...
Config file already exists. Skipping writing process.
Credentials file already exists. Skipping writing process.
Traceback (most recent call last):
  File "/path_to-dev_directory/test2.py", line 134, in <module>
    tru.run_dashboard(force=True)
  File "/path_to-dev_directory/venv/lib/python3.11/site-packages/trulens_eval/tru.py", line 1096, in run_dashboard
    raise RuntimeError(
RuntimeError: Dashboard failed to start in time. Please inspect dashboard logs for additional information.

  You can now view your Streamlit app in your browser.

Dashboard started at http://ip-address:8501 .
  Network URL: http://ip-address:8501

  External URL: http://ip-address:8501

Using legacy llama_index version None. Consider upgrading to 0.10.0 or later.
**Environment:**
 - OS: [Ubuntu]
 - Python - 3.11
 - TruLens 0.25.1
 - Versions of other relevant installed libraries

**Additional context**

**Comment by atulm-encora** [comment]
Please note even after giving the error the dashboard starts. The real problem is its not showing any feedback scores. Looks like it failed to capture it hence there are no scores present.

I also updated the version to 0.26, but issue is not resolved.

**Comment by joshreini1** [comment]
@atulm-encora it can take some time for feedbacks to be computed. As they will get kicked off after the record is created, in some cases it can appear that the evaluations didn’t run when in fact you may just need to wait for them to finish generation. Can you confirm that they do appear after a longer amount of time?

**Comment by atulm-encora** [comment]
I kept the code running for 1 hour, but no records were generated even after 1 hour. The terminal kept showing following info and just continuing

![image](https://github.com/truera/trulens/assets/133240997/c8b6848b-9c3e-40f8-a497-8a636898c0b6)

**Comment by DEBTHOMAZ** [comment]
Hello! 
I am having a similar issue, but in my case the feedback functions doesn't run at all, they all fail. Can you help me?

OS: Windows 10
Python - 3.10
TruLens - 0.28.2

**Comment by yuvneshtruera** [comment]
@DEBTHOMAZ Can you please create a new github issue and provide code/logs for us to reproduce the problem?

**Comment by DEBTHOMAZ** [comment]
@yuvneshtruera Ok! Here it is https://github.com/truera/trulens/issues/1125

**Comment by yuvneshtruera** [comment]
@atulm-encora Please let us know if you are still facing this issue. I am closing this issue for now.
