### ISSUE TITLE
[FEAT] Support for Python 3.12

### ISSUE THREAD

**Issue by j-dominguez9** [truera/trulens#1007]
**Feature Description**
Python 3.12 support, pretty self explanatory.

**Reason**
Because I can't install and use it with python 3.12.

**Importance of Feature**
This needs to happen, why not just update it on pypi now?

**Comment by joshreini1** [comment]
Addressed by https://github.com/truera/trulens/pull/1012

**Comment by joshreini1** [comment]
This support is merged and will be available in 0.27 later this week.

**Comment by joshreini1** [comment]
Hey @j-dominguez9  - python 3.12 support is now available in 0.27.0!

Please upgrade your trulens-eval version `pip install -U trulens-eval` and let me know if you have any issues - thanks!
