### ISSUE TITLE
[BUG] Dashboard ignores `database_url` when opening Apps or Evaluations pages without opening Leaderboards first

### ISSUE THREAD

**Issue by theoratkin** [truera/trulens#1017]
**Bug Description**
I spent many hours figuring out why the Streamlit dashboard seemingly randomly ignores the `database_url` and falls back to using `default.sqlite`. Turns out, if you happen to have Apps or Evaluations page opened at the moment you execute `run_dashboard`, then the `Tru` singleton is initialized with the default constructor, ignoring your `database_url`.

**To Reproduce**
1. Run the dashboard with your own database URL:
```python
DB_URL = 'postgresql+psycopg://test:12345678@localhost/test'
tru = Tru(database_url=DB_URL)
tru.run_dashboard()
```

2. Go either to http://localhost:8501/Apps or http://localhost:8501/Evaluations.
3. The page will be empty (even if you already have something in the database) and you will see a `default.sqlite` file created in the project directory.

**Expected behavior**
`database_url` is respected regardless of which dashboard page you open first.

**Relevant Logs/Tracebacks**
In the [Leaderboard.py](https://github.com/truera/trulens/blob/main/trulens_eval/trulens_eval/Leaderboard.py) the `database_url` is initialized by argument parser:

https://github.com/truera/trulens/blob/75c583889775ad3289ff24c0f5db7b9532d9e7ec/trulens_eval/trulens_eval/Leaderboard.py#L155-L169

However, there is no such logic in [Apps](https://github.com/truera/trulens/blob/main/trulens_eval/trulens_eval/pages/Apps.py) and [Evaluation](https://github.com/truera/trulens/blob/main/trulens_eval/trulens_eval/pages/Evaluations.py) pages, so the default singleton constructor is used.

https://github.com/truera/trulens/blob/75c583889775ad3289ff24c0f5db7b9532d9e7ec/trulens_eval/trulens_eval/pages/Evaluations.py#L55-L56

This relies on having the Leaderboard page opened before others.

**Environment:**
 - OS: Linux
 - Python Version: 3.11.8
 - TruLens version: 0.26.0

**Comment by joshreini1** [comment]
@piotrm0 can you take this one?

**Comment by piotrm0** [comment]
Hi @theoratkin , I believe I fixed this as part of another database-related PR (https://github.com/truera/trulens/pull/971). This should be in the next release but you can test with the PR version for now. Let me know if the issue persists.

**Comment by theoratkin** [comment]
Sorry for late reply, didn't have the chance to test it until now. Yes, it is indeed fixed now, thanks! Closing the issue.
