### ISSUE TITLE
[BUG] Groundedness and Context Relevance Error due to Debug Timeout

### ISSUE THREAD

**Issue by bhardwaj-vipul** [truera/trulens#1057]
**Bug Description**
I have been following Langchain [quickstart](https://github.com/truera/trulens/blob/main/trulens_eval/examples/quickstart/langchain_quickstart.ipynb) and getting the below error:

**Relevant Logs/Tracebacks**
```
python3.11/site-packages/trulens_eval/database/sqlalchemy_db.py - 273 - INFO - 🛑 feedback result context_relevance_with_cot_reasons FAILED feedback_result_hash_18d5d9a0beaa219c773969aea44bbfc8 - TP.submit with debug timeout_4
``` 
and,

```
python3.11/site-packages/trulens_eval/database/sqlalchemy_db.py - 273 - INFO - 🛑 feedback result groundedness_measure_with_cot_reasons FAILED feedback_result_hash_f74b317d2063c75b6028016f1dbe1a97 - TP.submit with debug timeout_1
```
**Environment:**
 - OS: MacOS
 - Python Version: 3.11
 - TruLens version: 0.27.2
 - langchain : 0.1.14
 - langchain-community: 0.0.31
 - langchain-core: 0.1.40
 - langchain-openai: 0.1.1 

**Additional context**
I am able to run the context relevance and groundedness directly.
```
provider.context_relevance_with_cot_reasons(question="abc", context="abcdef")
```

**Comment by piotrm0** [comment]
Hi @bhardwaj-vipul , I'm having trouble replicating. Are the other outputs in the notebook as expected? Specifically, the `display(rec)` in the `Retrieve records and feedback` section? If so, what does it show as the output there?

**Comment by joshreini1** [comment]
Hey @bhardwaj-vipul - can you give us an update to @piotrm0 's questions so we can help debug? Thanks!

**Comment by joshreini1** [comment]
Closing due to no response. @bhardwaj-vipul if this issue is ongoing and you're able to share more information to help reproduce, please re-open.
