### ISSUE TITLE
[BUG] Trulens does not evaluate the cost per inference in the case of Bedrock.

### ISSUE THREAD

**Issue by DhruvinKoshiya** [truera/trulens#1073]
**Bug Description**
I'm trying to evaluate RAG using Trulense with the Bedrock Llama 2 model, but in the Trulense dashboard, it does not provide the cost of inference. It only shows $0. If I use OpenAI instead of Bedrock Llama 2, then it shows the price for every inference.

**To Reproduce**
```
llm = Bedrock( model="meta.llama2-70b-chat-v1", profile_name=profile_name)

tru_recorder = TruChain(chain,app_id='ChatApplication', feedbacks=[feedback function])

with tru_recorder as recording:
    llm_response = llm.chat("What's the capital of the USA?")
display(llm_response)
```

**Expected behavior**
Trulens should provide the cost for every inference in any LLM.

**Relevant Logs/Tracebacks**
Trulens dashboard using Bedrock Llama 2 model.
![image](https://github.com/truera/trulens/assets/163841019/cc520cea-f7f6-4d96-83a8-b1a69674254d)

**Environment:**
 - OS: Windows
 - Python Version: 3.10.1
 - TruLens version: 0.27.0
 - Versions of other relevant installed libraries: llama-index==0.10.25

**Comment by piotrm0** [comment]
Hi @DhruvinKoshiya , do you know if Bedrock models are charged at some fixed rate that can be determined from model name?

**Comment by DhruvinKoshiya** [comment]
@piotrm0 - Bedrock modes are charged per the input and output token. This [document](https://aws.amazon.com/bedrock/pricing/?refid=33b5edcf-0d26-4e1d-b868-603c42c06eaf) provides pricing of all the models.
