### ISSUE TITLE
[BUG] TruChain - no values returned for Groundedness feedback function for Bedrock

### ISSUE THREAD

**Issue by mahesh-hv-appmod** [truera/trulens#1101]
**Bug Description**
TruEval returns an empty array for Groundedness values

**To Reproduce**
from langchain.chains import LLMChain
from langchain.schema import StrOutputParser
from langchain_core.runnables import RunnablePassthrough

retriever = vectorstore.as_retriever()

retrieval_chain = (
    {"context": retriever, "query": RunnablePassthrough()}
    | prompt_template
    | llm
    | StrOutputParser()
)

retrieval_chain.invoke(question)

from trulens_eval.app import App
from trulens_eval.feedback import Groundedness
from trulens_eval import TruChain, Feedback, Tru, Select, Bedrock

tru = Tru()
tru.reset_database()

context = App.select_context(retrieval_chain)

# Initialize model for feedback function collection class:
bedrock = Bedrock(model_id = "amazon.titan-tg1-large", region_name="us-east-1")

# Define a groundedness feedback function
grounded = Groundedness(groundedness_provider=bedrock)

f_groundedness = (
    Feedback(grounded.groundedness_measure_with_cot_reasons, name="Groundedness")
    .on(context.collect()) # collect context chunks into a list
    .on_output()
    .aggregate(grounded.grounded_statements_aggregator)
)
    
f_relevance = Feedback(bedrock.relevance, name="Relevance").on_input_output()

tru_recorder = TruChain(retrieval_chain,
    app_id='Base LLM',
    selectors_check_warning=True,                   
    feedbacks=[f_groundedness, f_relevance])

questions = [
    "What is Acme Co.?", 
    "Who are the competetiors?",
    "What’s the financial profile?"
  ]

with tru_recorder as recording:
    for question in questions:
        llm_response = retrieval_chain.invoke(question)

**Expected behavior**
expect to see some values for the Groundedness metric. Relevance metrics are being returned

**Environment:**
Python 3.10.13
langchain: 0.1.16
trulens_eval: 0.27.0

**Additional context**

**Comment by mahesh-hv-appmod** [comment]
small edit

the calls to the groundedness functions pass in empty arrays '[]'. see below:

![groundedness](https://github.com/truera/trulens/assets/77741042/b7d328b2-22cc-4d4e-ac9f-d5f81c89867f)

**Comment by vasokb** [comment]
Hi! I have exactly the same issue, both with context relevance as well as groundedness. I am using hugging face as the provider.
Any update on that?

**Comment by sfc-gh-jreini** [comment]
Hi @vasokb - since you're using a different provider, can you open a separate issue?

**Comment by sfc-gh-jreini** [comment]
Hey @mahesh-hv-appmod - was this ever resolved? If not, can you try with the latest trulens version (>=1.0) and let me know if it still persists?

**Comment by mahesh-hv-appmod** [comment]
have not checked in a while. will try with the latest (> v1.0) and update this thread

**Comment by sfc-gh-jreini** [comment]
thank you!

**Comment by sfc-gh-chu** [comment]
Hi @mahesh-hv-appmod following up, any luck with >1.0?

**Comment by sfc-gh-chu** [comment]
Closing this for now. Feel free to reopen if the issue comes up again
