### ISSUE TITLE
[BUG] Could not locate app.retriever.get_relevant_documents.rets[:].page_content.collect() in app/record.

### ISSUE THREAD

**Issue by AraHema** [truera/trulens#1132]
using this code 

def trulens_recorder(query_engine, app_id):
    """
    Get trulens recorder
    """
    openai = OpenAI(deployment_name="name of the model")

    qa_relevance = (
        Feedback(openai.relevance_with_cot_reasons, name="Answer Relevance")
        .on_input_output()
    )

    qs_relevance = (
        Feedback(openai.qs_relevance_with_cot_reasons, name = "Context Relevance")
        .on_input()
        .on(Select.RecordCalls.retriever.get_relevant_documents.rets[:].page_content.collect())
        .aggregate(np.mean)
    )

    grounded = Groundedness(groundedness_provider=openai)

    groundedness = (
        Feedback(grounded.groundedness_measure_with_cot_reasons, name="Groundedness")
        .on(Select.RecordCalls.retriever.get_relevant_documents.rets[:].page_content.collect())
        .on_output()
        .aggregate(grounded.grounded_statements_aggregator)
    )

    feedbacks = [qa_relevance, qs_relevance, groundedness]
    tru_recorder = TruChain(
        query_engine,
        app_id=app_id,
        feedbacks=feedbacks
    )
    return tru_recorder
    
    i'm currently using a retirval.qa chain and just use LCEL like
     RunnableAssign({"original_text": itemgetter("query")}) | retival_chain
     
     i faced the issue that it can't find the retriver key but when i remove the useage of LCEL and just use retival_chain ... it passed
     
     
     is there an issue when i'm using LCEL?

**Comment by AraHema** [comment]
@yuvneshtruera  Do you have any recommended solution?

**Comment by joshreini1** [comment]
No issue with LCEL - but the structure can be different, leaving the context at a different location in your application then you're specifying with the feedback selector. Can you share your LCEL setup so we can help? @AraHema

**Comment by AraHema** [comment]
@joshreini1  something like that RunnableAssign({"original_text": itemgetter("query")}) | retival_chain
where retrival_chain is a RetrivalQA chain

**Comment by sfc-gh-jreini** [comment]
Here's an example of how to work with the Langchain ensemble retriever. Let me know if this helps: https://github.com/truera/trulens/blob/main/trulens_eval/examples/expositional/frameworks/langchain/langchain_ensemble_retriever.ipynb
