### ISSUE TITLE
Outdated documentation for Groundedness

### ISSUE THREAD

**Issue by Arseniy-II** [truera/trulens#1149]
**Bug Description**
[Here is the reference for the old use of Groundedness](https://www.trulens.org/trulens_eval/evaluation/feedback_evaluations/groundedness_benchmark/)

**Expected behavior**
According to the [recent updated](https://github.com/truera/trulens/pull/1135) it should be used differently

**Comment by joshreini1** [comment]
Fixed by https://github.com/truera/trulens/pull/1161

**Comment by opyate** [comment]
> AttributeError: 'Groundedness' object has no attribute 'grounded_statements_aggregator'

```
pip freeze | grep trulens                         
trulens==1.0.6
trulens-apps-langchain==1.0.6
trulens-apps-llamaindex==1.0.6
trulens-core==1.0.6
trulens-dashboard==1.0.6
trulens-feedback==1.0.6
trulens-providers-openai==1.0.5
trulens_eval==1.0.6
```

**Comment by wushanyun64** [comment]
> > ImportError: cannot import name 'Groundedness' from 'trulens.feedback'
> 
> And then trying `from trulens.feedback.v2.feedback import Groundedness`:
> 
> > AttributeError: 'Groundedness' object has no attribute 'grounded_statements_aggregator'
> 
> ```
> pip freeze | grep trulens                         
> trulens==1.0.6
> trulens-apps-langchain==1.0.6
> trulens-apps-llamaindex==1.0.6
> trulens-core==1.0.6
> trulens-dashboard==1.0.6
> trulens-feedback==1.0.6
> trulens-providers-openai==1.0.5
> ```

I have the same error
