### ISSUE TITLE
[BUG] Bedrock provider always gives: "Groundedness per statement in source:   0%"

### ISSUE THREAD

**Issue by Arseniy-II** [truera/trulens#1150]
**Bug Description**
I'm following quickstart with [langChain](https://www.trulens.org/trulens_eval/getting_started/quickstarts/langchain_quickstart/#send-your-first-request)
However, I want to use Bedrock as an LLM and as an evaluation provider. I'm able to get answer relevance and context relevance but groundedness doesn't appear on a dashboard and I'm getting "Groundedness per statement in source:   0%| "

**To Reproduce**
Follow [quickstart](https://www.trulens.org/trulens_eval/getting_started/quickstarts/langchain_quickstart/) with few tweaks:
1. instead of `llm = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0)` use `from langchain_aws import ChatBedrock`
2. instead of `embeddings = OpenAIEmbeddings()` use `from langchain_community.embeddings import BedrockEmbeddings`
3. instead of `provider = OpenAI()` use `from trulens_eval.feedback.provider import Bedrock`

**Expected behaviour**
Groundedness should be present on a dashboard and should be higher than 0 for the question mentioned in the [quickstart](https://www.trulens.org/trulens_eval/getting_started/quickstarts/langchain_quickstart/)

**Relevant Logs/Tracebacks**
```
✅ In Groundedness, input source will be set to __record__.app.first.steps__.context.first.get_relevant_documents.rets.collect() .
✅ In Groundedness, input statement will be set to __record__.main_output or `Select.RecordOutput` .
✅ In relevance, input prompt will be set to __record__.main_input or `Select.RecordInput` .
✅ In relevance, input response will be set to __record__.main_output or `Select.RecordOutput` .
✅ In context_relevance_with_cot_reasons, input question will be set to __record__.main_input or `Select.RecordInput` .
✅ In context_relevance_with_cot_reasons, input context will be set to __record__.app.first.steps__.context.first.get_relevant_documents.rets .
Starting dashboard ...
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/Arseniy_Ivanov/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
Groundedness per statement in source:   0%|                                        | 0/3 [00:00<?, ?it/s]
```

**Environment:**
 - OS: MacOS
 - Python Version: Python 3.12.2
 - TruLens version: trulens_eval==0.29.0

**Comment by Arseniy-II** [comment]
I have collected context exactly like that and looks like it is collected properly

**Comment by Arseniy-II** [comment]
So far I figured out that `generate_score_and_reasons` methods fail silently. It would be very beneficial to have some error provided back if methods fail

**Comment by Arseniy-II** [comment]
in bedrock.py in method _create_chat_completion

for amazon.titan-text-express-v1 
json.loads(response.get('body').read()) returns empty string

for 'anthropic.claude-3-sonnet-20240229-v1:0'
json.loads(response.get('body').read()) returns empty string

I believe it is because the body is formatted in the wrong way
It looks like this:
```
body = json.dumps(
    {
        "prompt": f"\n\nHuman:{messages_str}\n\nAssistant:",
        "temperature": 0,
        "top_p": 1,
        "max_tokens_to_sample": 4095
    }
```
But it should be like this:
```
bodyNew = json.dumps(
    {
        "system": "Respond as helpfull assistant", 
        "messages": [{"role": "user", "content": f"\n\nHuman:{messages_str}\n\nAssistant:"}], 
        "anthropic_version": "bedrock-2023-05-31",
        "max_tokens": 4095,
    }
)
```

**Comment by joshreini1** [comment]
Thanks @Arseniy-II - will take a look
