### ISSUE TITLE
[FEAT] ARES integration possible?

### ISSUE THREAD

**Issue by DallanQ** [truera/trulens#1153]
**Feature Description**
Is it possible to integrate Trulens with ARES (Stanford)? Is the recommended way to train the judges outside of Trulens and then use them in Trulens as custom feedback functions?

**Reason**
I'd like to have an easy way to compare ARES and Trulens stock evaluations.

**Importance of Feature**
To be honest, I'm not sure how much this is needed. I like the ARES approach theoretically, but I can't say whether it is better than the Trulens approach.

**Comment by joshreini1** [comment]
Hi @DallanQ - the ARES workflow seems a bit at odds with feedback functions, requiring a lot of setup and data to get started. If you've already got ARES results though, it wouldn't be that hard to generate TruLens evaluations from your data using the `TruVirtual`class ([example notebook](https://www.trulens.org/trulens_eval/getting_started/quickstarts/existing_data_quickstart/)).

**Comment by DallanQ** [comment]
Thanks @joshreini1 - I'm still exploring this space, and that notebook helps.

**Comment by DrewGalbraith** [comment]
### Follow-up
Hey @DallanQ,
- First off, we video called once about DL and family history like 2 years ago :) 
- Second, I don't see a PR or fork linked here, and searching '_ares_' in the repo doesn't bring anything up. Did you ever get this working? I'd love to see how if you did, so as to not reinvent the wheel.

**Comment by DallanQ** [comment]
Hi @DrewGalbraith nice to connect again :-)  I ended up going a different direction. I split retrieval evaluation and answer-synthesis evaluation into separate evaluation efforts and used a more traditional approach for retrieval evaluation.
