### ISSUE TITLE
[BUG] Inconsistent results between records variable values and dashboard/leaderboard values

### ISSUE THREAD

**Issue by marko-radovic96** [truera/trulens#1162]
**Bug Description**
I am building simple RAG application using few pages from wikipedia.
Values for Groundedness, Answer Relevance and Context's Relevance are not the same between ```records``` variable (output of ```tru.get_records_and_feedback(app_ids=[])``` code) and dashboard values.
Also, feedback variable does not contain Context's Relevance feedback function name.

**To Reproduce**
```
from trulens_eval import Tru
from trulens_eval.app import App
from trulens_eval import OpenAI as fOpenAi
from trulens_eval import Feedback
from trulens_eval import TruLlama

tru = Tru()
tru.reset_database()

provider = fOpenAi()

context = App.select_context(query_engine)

# Define a groundedness feedback function
f_groundedness = (
    Feedback(provider.groundedness_measure_with_cot_reasons, name="Groundedness")
    .on(context.collect()) # collect context chunks into a list
    .on_output()
)

# Question/answer relevance between overall question and answer.
f_answer_relevance = (
    Feedback(provider.relevance, name="Answer Relevance")
    .on_input_output()
)
# Question/statement relevance between question and each context chunk.
f_context_relevance = (
    Feedback(provider.context_relevance_with_cot_reasons, name="Context's Relevance")
    .on_input()
    .on(context)
    .aggregate(np.mean)
)

tru_query_engine_recorder = TruLlama(query_engine,
    app_id='LlamaIndex_App1',
    feedbacks=[
        f_groundedness, 
        f_answer_relevance, 
        f_context_relevance])

questions = ["question 1", "question 2"]
for question in questions:
    with tru_query_engine_recorder as recording:
        query_engine.query(question)

records, feedback = tru.get_records_and_feedback(app_ids=[])

tru.run_dashboard()
```

**Expected behavior**
Values in leaderboard match values in ```record``` variable.
```feedback``` variable values match all defined feedback function names.

**Relevant Logs/Tracebacks**

Output when feedback functions are initialized:
✅ In Groundedness, input source will be set to __record__.app.query.rets.source_nodes[:].node.text.collect() .
✅ In Groundedness, input statement will be set to __record__.main_output or `Select.RecordOutput` .
✅ In Answer Relevance, input prompt will be set to __record__.main_input or `Select.RecordInput` .
✅ In Answer Relevance, input response will be set to __record__.main_output or `Select.RecordOutput` .
✅ In Context's Relevance, input question will be set to __record__.main_input or `Select.RecordInput` .
✅ In Context's Relevance, input context will be set to __record__.app.query.rets.source_nodes[:].node.text .

```feedback``` variable does not contain Context's Relevance value:
```
pd.set_option("display.max_colwidth", None)
records[["input", "output"] + feedback]
```
<img width="678" alt="Screenshot_38" src="https://github.com/truera/trulens/assets/89461159/46826e96-3666-4b55-bb3d-42dcee1c1e73">

Values in dashboard/leaderboard are not the same as ```records```:
<img width="657" alt="Screenshot_39" src="https://github.com/truera/trulens/assets/89461159/1fcd9cd9-782b-4059-8820-15459bbdec87">

**Environment:**
 - OS: Windows 10
 - Python Version: 3.9.13
 - TruLens version: 0.29.0
 - llama-index version: 0.10.38

**Additional context**
/

**Comment by marko-radovic96** [comment]
Tried to replace
```
f_answer_relevance = (
    Feedback(provider.relevance, name="Answer Relevance")
    .on_input_output()
)
```
with
```
f_answer_relevance = (
    Feedback(provider.relevance_with_cot_reasons, name="Answer Relevance")
    .on_input_output()
)
```
but still doesn't work.

**Comment by joshreini1** [comment]
It looks like the screenshots you have here were taken at different times and the feedback was not finished computing. By default, feedback results are computed asyncronously so as not to slow down your app and may not yet be available whenever you first view the results (via the notebook or dashboard).

**Comment by joshreini1** [comment]
If you want to ensure the feedback results are available when you check for them, you can block on their computation.

You can use `as_completed` to wait until they have finished evaluating or use the utility method:

```python
for feedback, feedback_result in rec.wait_for_feedback_results().items():
    print(feedback.name, feedback_result.result)

# See more about wait_for_feedback_results:
# help(rec.wait_for_feedback_results)
```

**Comment by marko-radovic96** [comment]
Hi @joshreini1 ,

Thank you for your response.
When I added `tru_query_engine_recorder.wait_for_feedback_results()` before `records, feedback = tru.get_records_and_feedback(app_ids=["LlamaIndex_App1"])` line, all feedbacks are present in `records` variable.

But, still some values are not the same in `records` variable and in dashboard.
<img width="718" alt="Screenshot_1" src="https://github.com/truera/trulens/assets/89461159/a3e5a46e-2e0f-4bca-b69a-81383417c382">

<img width="555" alt="Screenshot_2" src="https://github.com/truera/trulens/assets/89461159/59d00a01-2b7f-401a-bec1-0ef4e7dd2ff6">

Context relevance for question 5 is NaN in `records` variable, but it is 0.7 in dashboard. Why?
Also, what does that mean when value is NaN?

**Comment by joshreini1** [comment]
@marko-radovic96 when the value is NaN, it means that the feedback has not computed yet (or failed to compute). Other than the discrepancy in NaNs (which I think should go away if this data is loaded from your trulens db (`default.sqlite` by default) at the same time.
