### ISSUE TITLE
Deploy Trulens with FastAPI

### ISSUE THREAD

**Issue by Nishant01-ai** [truera/trulens#1164]
1) What is the approach to deploy trulens with FastAPI ?
2) How to run tru.run_dashboard() in a single container with FastAPI with Uvicorn Server ?

**Comment by joshreini1** [comment]
@dosu response is good here. Let us know if you have issues

**Comment by sfc-gh-jreini** [comment]
No further work planned on this.

**Comment by piotrm0** [comment]
@sfc-gh-chu also had some issues with working with an app defined by fastapi endpoints.
