### ISSUE TITLE
from trulens_eval.feedback import Groundedness Not working

### ISSUE THREAD

**Issue by saccpp** [truera/trulens#1170]
ImportError: cannot import name 'Groundedness' from 'trulens_eval.feedback'

**Comment by joshreini1** [comment]
Hey @saccpp - groundedness is now available from the provider itself to make it easier and faster to use! This was changed in 0.29, and you can read more about the change in the release notes!

https://github.com/truera/trulens/releases/tag/trulens-eval-0.29.0

**Comment by joshreini1** [comment]
Hey @saccpp - groundedness is now available from the feedback provider, similar to how the other feedback functions are called. This was changed to reduce the code you have to write and make it more straightforward to use.

Read more about the change in the 0.29 release notes here: https://github.com/truera/trulens/releases/tag/trulens-eval-0.29.0

**Comment by Dannyjelll** [comment]
Is this still missing for the AzureOpenAI provider? Does not work with it for me
