### ISSUE TITLE
Python Quick Start (no notebook)

### ISSUE THREAD

**Issue by krishangupta** [truera/trulens#127]
I don't use Jupyter notebook, but I do use LLMs. Could have a quick start that doesn't require Jupyter?

**Comment by rshih32** [comment]
Hi [krishangupta](https://github.com/krishangupta),

Can you see if the below is what you might be looking for? If so we can add it in.
https://github.com/truera/trulens/blob/quickstart_non_jupyter/trulens_eval/trulens_eval_quickstart.py

Note: don't forget to add API keys or you will run into authentication errors
At the start of the quickstart you will want to fill in environment variables, or you can set them outside the script too
```
os.environ["OPENAI_API_KEY"] = "..."
os.environ["HUGGINGFACE_API_KEY"] = "..."
```

**Comment by rshih32** [comment]
This is now here in main
https://github.com/truera/trulens/blob/main/docs/trulens_eval/quickstart.py
