### ISSUE TITLE
[BUG]Metric calculation and corresponding interpretation

### ISSUE THREAD

**Issue by kmr666** [truera/trulens#1290]
**Bug Description**
What happened?
1）I tried to use other frameworks such as ragas and trulens to calculate context_relevance for my data sets, but the two frameworks gave different results.Is it because of different calculation methods?
2）My understanding is that trulens uses llm to participate in the evaluation. May I ask whether the evaluation of trulens only requires the designation of an llm and does not require the calculation of indicators using the embedding model?
3）Are there any relationships and differences between context_relevance and context_relevance_with_cot_reasons for metrics in trulens？
**To Reproduce**
Which steps should someone take to run into the same error? A small, reproducible code example is useful here.

**Expected behavior**

**Relevant Logs/Tracebacks**
Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks. If the issue is related to the TruLens dashboard, please also include a screenshot.

**Environment:**
 - OS: [e.g. MacOS, Windows]
 - Python Version
 - TruLens version
 - Versions of other relevant installed libraries

**Additional context**

**Comment by sfc-gh-jreini** [comment]
@dosu is right here. We will be adding new context relevance benchmarks to our [benchmarks page](https://www.trulens.org/trulens_eval/evaluation_benchmarks/) soon.
