### ISSUE TITLE
Way to get fixed selector call even if RAG structure is changing.

### ISSUE THREAD

**Issue by poojatambe** [truera/trulens#1300]
**Bug Description**
Implemented a hybrid retriever RAG with feedback functions to evaluate it. Then improved RAG with multiple index. The selector for context got changed. Is there any way to get fixed selector call for getting context to find context relevance and groundedness?

**To Reproduce**
Which steps should someone take to run into the same error? A small, reproducible code example is useful here.

**Expected behavior**

**Relevant Logs/Tracebacks**
Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks. If the issue is related to the TruLens dashboard, please also include a screenshot.

**Environment:**
 - OS: [e.g. MacOS, Windows]
 - Python Version
 - TruLens version
 - Versions of other relevant installed libraries

**Additional context**

**Comment by poojatambe** [comment]
Hi, 
Getting error with ```context = App.select_context(rag_chain)``` :
**"Cannot find any `BaseRetriever` in app."**

**Comment by sfc-gh-pdharmana** [comment]
@poojatambe closing this for now. pls reopen if you still need help
