### ISSUE TITLE
[FEAT] Check typing with Mypy and add py.typed file

### ISSUE THREAD

**Issue by cbornet** [truera/trulens#1310]
**Feature Description**
It seems the trulens project makes efforts to type the code.
I haven't found that types are checked in CI (are they?). It would be nice to do a check with a tool such as Mypy in CI.
Then a [PEP561 py.typed file](https://peps.python.org/pep-0561/#packaging-type-information) could be added to the package so types can be used in projects that import trulens.

**Reason**
This will increase quality and probably uncover some bugs.

**Importance of Feature**
Currently when importing trulens in a project and checking it with mypy, trulens types are not imported.

**Comment by sfc-gh-jreini** [comment]
@coreyhu You might have added this in upcoming changes. Can you confirm?
