### ISSUE TITLE
[Request] Make code snippets copy-able on How to use TruLens page

### ISSUE THREAD

**Issue by nikhil-vytla** [truera/trulens#142]
## Background
- Currently, the [How to use TruLens page](https://www.trulens.org/how-to-use.html) displays 3 code snippets as PNGs. These PNGs are both static and resolution is impacted depending on the user's screen.

## Request
- Replace snippet PNGs with copy-able code snippets for ease of use, accessibility, and ease of maintenance (ideal), OR
- Add hyperlinks to respective files/gists with code represented in PNGs.

**Comment by joshreini1** [comment]
how-to-use trulens page is removed, but https://github.com/truera/trulens/pull/358 makes code blocks in all of the docs copyable.
