### ISSUE TITLE
[FEAT] Inject a client record_id

### ISSUE THREAD

**Issue by ruifcruz** [truera/trulens#1429]
**Feature Description**
When using TruChain, inject a record_id (or an external record_id) when the chain is ran

```
with tru_recorder as recording:
    llm_response = rag_chain.invoke("What is Task Decomposition?")
```

**Reason**
I have all my inputs on a Pandas df. When i get the records dataframe it would be extremely useful to easily join the records df with the original df

**Comment by sfc-gh-jreini** [comment]
Hey @ruifcruz - you can do this today!

with tru_recorder as recording:
    # inject the record metadata to records until this is changed.
    recording.record_metadata=dict(external_record_id=<your id here>)
    llm_response = rag_chain.invoke("What is Task Decomposition?")

**Comment by ruifcruz** [comment]
Thank you @sfc-gh-jreini 🙏
