### ISSUE TITLE
[BUG] Langchain Provider _create_chat_completion crashing

### ISSUE THREAD

**Issue by alonlahav123** [truera/trulens#1451]
**Bug Description**
What happened?
Hi Trulens team, I was trying to use the trulens langchain provider object with a custom langchain LLM object but when I tried to calculate the relevance score it crashed. I get the error that 'str' object has no attribute 'content'.

**To Reproduce**
Run the following script:

```
from typing import Any, List, Optional
from langchain_core.callbacks.manager import CallbackManagerForLLMRun
from langchain_core.language_models.llms import LLM
from trulens.providers.langchain import Langchain


class CustomLLM(LLM):
    n: int

    def _call(
        self,
        prompt: str,
        stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> str:
        if stop is not None:
            raise ValueError("stop kwargs are not permitted.")
        return prompt[: self.n]

    @property
    def _llm_type(self) -> str:
        return "custom"


llm = CustomLLM(n=5)
langchain_provider = Langchain(chain=llm)
rel = langchain_provider.relevance(
    prompt="Where is Germany?",
    response="Germany is in Earth."
)
print(rel)
```

**Expected behavior**
I expect the above code to print the relevance score without crashing.

**Relevant Logs/Tracebacks**

langchain request failed <class 'AttributeError'>='str' object has no attribute 'content'. Retries remaining=3.
langchain request failed <class 'AttributeError'>='str' object has no attribute 'content'. Retries remaining=2.
langchain request failed <class 'AttributeError'>='str' object has no attribute 'content'. Retries remaining=1.
langchain request failed <class 'AttributeError'>='str' object has no attribute 'content'. Retries remaining=0.
Traceback (most recent call last):
  File "C:\Users\alonl\PycharmProjects\pythonProject\test_provider.py", line 65, in <module>
    rel = langchain_provider.relevance(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alonl\PycharmProjects\pythonProject\.venv\Lib\site-packages\trulens\feedback\llm_provider.py", line 525, in relevance
    return self.generate_score(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alonl\PycharmProjects\pythonProject\.venv\Lib\site-packages\trulens\feedback\llm_provider.py", line 105, in generate_score
    response = self.endpoint.run_in_pace(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alonl\PycharmProjects\pythonProject\.venv\Lib\site-packages\trulens\core\feedback\endpoint.py", line 323, in run_in_pace
    raise RuntimeError(
RuntimeError: Endpoint langchain request failed 4 time(s): 
	'str' object has no attribute 'content'
	'str' object has no attribute 'content'
	'str' object has no attribute 'content'
	'str' object has no attribute 'content'

**Environment:**

- OS: both MacOS and Windows
- Python Version: 3.12.0
- TruLens version: 1.0.1
- trulens-providers-langchain version: 1.0.1

**Additional context**
I think I have an idea of what is happening which I hope helps:

When you go into the Langchain object you can see that it takes both BaseLLM and BaseChatModel classes as its "chain" attribute. Although both have the invoke method each of their invoke methods returns a different value, the BaseLLM's invoke returns a string while the BaseChatModel's invoke returns a BaseMessage object. This creates an issue in the Langchain object's _create_chat_completion method, specifically if the following statement goes through: `predict = self.endpoint.chain.invoke(messages, **kwargs).content`. It then calls invoke() and tries to extract the content attribute assuming its a BaseMessage which works if you are using a BaseChatModel but if you are using a BaseLLM model it will crash given that invoke() returns a string.

**Comment by sfc-gh-jreini** [comment]
Hey @alonlahav123 - we just released support for `BaseLLM` use in the Langchain provider in TruLens 1.0.2.

Give it a try and re-open if the issue persists. Thanks!
