### ISSUE TITLE
[BUG] Langchain vs LangChain in providers

### ISSUE THREAD

**Issue by ThomasZiegenhein** [truera/trulens#1454]
**Bug Description**
import error

**To Reproduce**
from trulens.providers.langchain import LangChain (see https://www.trulens.org/reference/trulens/providers/langchain/#trulens.providers.langchain)

**Expected behavior**
No import error

**Relevant Logs/Tracebacks**
-

**Environment:**

- OS: Ubuntu
- Python Version: 3.12
- TruLens version
trulens-core==1.0.1
trulens-feedback==1.0.1
trulens-providers-langchain==1.0.1

**Additional context**
Probably Typo in Documentation, either change Documentation or go with LangChain for object name

**Comment by sfc-gh-jreini** [comment]
@dosu you are confusing tru chain used for wrapping langchain apps and the langchain feedback provider.

**Comment by ThomasZiegenhein** [comment]
Sorry wasn't 100% clear I guess, the Example in the documentation says:

`from trulens.providers.langchain import LangChain`

but the object inside the providers is called Langchain, so what will work:

`from trulens.providers.langchain import Langchain`

... took some time for me to find that out, perhaps changing the documentation is the easiest way.

Thanks

**Comment by sfc-gh-jreini** [comment]
Sorry for the confusion here @ThomasZiegenhein - we'll look at standardizing this better and making docs more clear :)
