### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 2: illegal multibyte sequence

### ISSUE THREAD

**Issue by beatG123** [truera/trulens#1466]
**Bug Description**
I am trying to use TruLens to evaluate metrics for my RAG (Retrieval-Augmented Generation) program. My program uses Chinese text, and I'm encountering encoding errors somewhere within TruLens. Could you please advise on how to modify this?

**To Reproduce**
# -*- coding: utf-8 -*-
from utils import *
from langchain.chains import LLMChain

query = "如何确保不同部门之间的协调合作以有效推进大规模设备更新计划？"

# 1. 创建LLM链
vdb = Chroma(
    persist_directory=os.path.join(PROJECT_PATH, './data/.nnew_document_db'),
    embedding_function=get_embeddings_model(),
)
# 召回并过滤文档
documents = vdb.similarity_search_with_relevance_scores(query, k=5)
query_result = [doc[0].page_content for doc in documents if doc[1] > 0.5]
if len(query_result) == 0:
    policy_result = '未检索到相关的政策信息。'
    print(policy_result)
# 填充提示词并总结答案
prompt = PromptTemplate.from_template(RETRIVAL_PROMPT_TPL_01)
retrival_chain = LLMChain(
    llm = get_llm_model(),
    prompt = prompt,
    verbose = VERBOSE,
)
inputs = {
    'query': query,
    'query_result': '\n\n'.join(query_result) if len(query_result) else '没有查到',
}

# 创建TruLens反馈函数
from trulens_eval import TruChain, Tru, Feedback, OpenAI as TruOpenAI

tru_openai = TruOpenAI()
relevance = Feedback(tru_openai.relevance).on_input_output()
sentiment = Feedback(tru_openai.sentiment).on_output()

# 使用TruChain包装LangChain应用
truchain = TruChain(
    retrival_chain,
    app_id="LangChain_Assistant",
    feedbacks=[relevance, sentiment]
)

# 使用应用并记录结果
response = truchain.with_(retrival_chain, inputs)

# 运行仪表板查看结果
tru = Tru()
tru.run_dashboard(port=8502)

**Expected behavior**

**Relevant Logs/Tracebacks**
Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks. If the issue is related to the TruLens dashboard, please also include a screenshot.

**Environment:**

- Windows 10
- Python Version：3.10.9
- TruLens version：0.24.1

**Comment by beatG123** [comment]
I didn't understand. Please provide the complete code.

**Comment by sfc-gh-chu** [comment]
@beatG123 The encoding issue should be resolved in a later release. Could you try upgrading to `trulens-eval==0.33.1` or  `trulens==1.0.2`?

**Comment by beatG123** [comment]
> @beatG123 The encoding issue should be resolved in a later release. Could you try upgrading to `trulens-eval==0.33.1` or `trulens==1.0.2`?

Sure, I'll try it. If you have a better solution, please tell me. Thank you.

**Comment by sfc-gh-chu** [comment]
@beatG123 did this help?

**Comment by sfc-gh-pdharmana** [comment]
@beatG123 closing this for now, pls reopen if you need help again
