### ISSUE TITLE
Request to add functionality to Trulens to measure Latency

### ISSUE THREAD

**Issue by kangarooz** [truera/trulens#148]
By measuring latency, we can compare how effective these models are across different implementations. I believe it would be beneficial for evaluating and comparing the performance of this wrapper. Particularly, working with an e-GPU but in a Sequential process, it may help triage bottleneck issues.

**Comment by joshreini1** [comment]
Feature coming in the next release (likely Tuesday)

**Comment by sfc-gh-jreini** [comment]
TruLens 2.8 will include a Run API with built-in per-invocation timing. The `run.start()` method tracks wall-clock time for each record in the batch, and `run.get_records()` surfaces this data. This addresses the original request for latency measurement as a first-class feature.

PR: https://github.com/truera/trulens/pull/2391
