### ISSUE TITLE
Issue: TruSession and get_records_and_feedback() displaying results before feedback function results are populated

### ISSUE THREAD

**Issue by paul-gleeson** [truera/trulens#1501]
**Bug Description**
After using TruChain and LLMChain to complete my LLM pipeline, I'm trying to access feedback functions from the generated output. After I first run the command to generate a LLM response, the feedback function columns haven't 1) been created in the datatrame 2) been populated in the dataframe. 

When I run it a second time with the same command, the feedback function columns have appeared and are now populated from the previous run, but are now NAN for the current run. This delay in populating the feedback continues as I continue to generate new responses. 

**To Reproduce**
Assuming llm_chain is a fully functional LLMChain:

from trulens.providers.huggingface import Huggingface
from trulens.core import Feedback
from trulens.core import TruSession
from trulens.apps.langchain import TruChain
from trulens.dashboard import run_dashboard

session = TruSession()

# Define a pii_detection feedback function using HuggingFace.
f_pii_detection = Feedback(hugs.pii_detection_with_cot_reasons).on_input()

tru_recorder = TruChain(
    llm_chain, app_name="Chain1_ChatApplication", feedbacks=[f_pii_detection]
)

with tru_recorder as recording:
    prompt_input = "What is the typical weather in Ireland?"
    llm_response = llm_chain(prompt_input)
    
dataframe, feedback = session.get_records_and_feedback()
    
for i in range(len(dataframe)):
    print(dataframe.iloc[i])

**Environment:**

- Python==3.10
- TruLens==1.0.2
- Langchain== 0.3.0

**Comment by paul-gleeson** [comment]
Solved!! Thank you

**Comment by paul-gleeson** [comment]
@dosu this worked for the first few calls but then afterwards it has stopped populating my results. It returns NaN for language_match and toxic. And has a 1 from a previous call I made to my LLM. Below is a code snippet.

```
f_pii_detection = Feedback(hugs.pii_detection_with_cot_reasons).on_input()
f_hallucination = Feedback(hugs.language_match).on_input_output()
f_toxicity = Feedback(hugs.toxic).on_input()


tru_recorder = TruChain(
    llm_chain, app_name="Chain1_ChatApplication", feedbacks=[f_pii_detection, f_hallucination, f_toxicity]
)

with tru_recorder as recording:
    prompt_input = "Who is Bob the dog?"
    llm_response = llm_chain(prompt_input)


record = recording.get()

feedback_results = list(
    session.run_feedback_functions(
        record=record,
        feedback_functions=[f_pii_detection, f_hallucination, f_toxicity],
        app=tru_recorder,
        wait=True,
    )
)

# Add to db
session.add_feedbacks(feedback_results)    
    

dataframe, feedback = session.get_records_and_feedback()
    
# Print the DataFrame
for i in range(len(dataframe)):
    print(dataframe.iloc[i])
```

When I take a closer look, the toxic_calls and language_match_calls retun [] where as in previous runs, they were populated with the input and output text.

Reposting to correctly tag @dosu

**Comment by sfc-gh-jreini** [comment]
Hey @paul-gleeson - @dosu's suggestion is not accurate.

There is an expected delay between when you log the app's execution and the feedback computation being completed. We handle the feedback function computation async/in the background by default, so you may not see it if you look at the dashboard before it's ready.

If you want to wait until the feedback is completed, you can use the below:

```
with tru_recorder as recording:
    prompt_input = "What is the typical weather in Ireland?"
    
record = recording.get()

# Wait for the result futures to be completed and print them.
for feedback, result in record.wait_for_feedback_results().items():
    print(feedback.name, result.result)
```

**Comment by paul-gleeson** [comment]
Ok thanks for the help!
