### ISSUE TITLE
[BUG] why not found trulens.providers after pip install trulens 

### ISSUE THREAD

**Issue by jianhuisu** [truera/trulens#1579]
not found trulens.providers dic after use pip install trulens.  

i follow this flow https://www.trulens.org/getting_started/quickstarts/quickstart/

**Comment by jianhuisu** [comment]
![image](https://github.com/user-attachments/assets/83b662c0-988b-4a11-a5e7-4d44a6f60551)

**Comment by sfc-gh-jreini** [comment]
Hi @jianhuisu - you need to install `trulens-providers-openai`, this is included in the `pip install` cell at the top of the notebook.

**Comment by jianhuisu** [comment]
> Hi @jianhuisu - you need to install `trulens-providers-openai`, this is included in the `pip install` cell at the top of the notebook.

thank you , i was careless
