### ISSUE TITLE
[BUG] Snowflake Connector gives error when using active snowpark session in "Streamlit in Snowflake"

### ISSUE THREAD

**Issue by cwitt2013** [truera/trulens#1596]
**Bug Description**
When I want to create a connection to the Snowflake within "Streamlit in Snowflake" (thus, during running a Streamlit App on Snowflake Warehouse) it gives the following error message

`ValueError: Connection parameters missing from provided `snowpark_session`: ['user']`

This error does not occur when using the same code line in e.g. Snowflake Notebooks.

**To Reproduce**
1. Create a a simple Streamlit App for "Streamlit in Snowflake"
2. Add a snowflake connection using the following code line 
```
from snowflake.snowpark.context import get_active_session
from trulens.connectors.snowflake import SnowflakeConnector
tru_snowflake_connector = SnowflakeConnector(
    snowpark_session=get_active_session(),
    database_redact_keys=True
)
```
3. Publish the streamlit app on snowflake

**Expected behavior**
The Trulens snowflake connector should use the active snowflake connection (or snowpark session) and create a trulens connection to the database.

**Relevant Logs/Tracebacks**
File "/usr/lib/python_udf/49145eaa7707ed0d820f39c30a83d26d83795c04529fe37a973e19b64ed3abd5/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
File "/tmp/appRoot/app.py", line 14, in <module>
    tru_snowflake_connector = SnowflakeConnector(
File "/usr/lib/python_udf/49145eaa7707ed0d820f39c30a83d26d83795c04529fe37a973e19b64ed3abd5/lib/python3.10/site-packages/trulens/connectors/snowflake/connector.py", line 101, in __init__
    raise ValueError(

**Environment:**

- OS: Linux
- Python Version: 3.10
- TruLens version: 1.1.0
- Versions of other relevant installed libraries
- streamlit: 1.35.0
- snowflake-snowpark-python: 1.18.0

**Additional context**
Here you will find a screenshot of the error and a screenshot for the same code in Snowflake Notebooks.

![image](https://github.com/user-attachments/assets/017b6051-547a-4438-93c5-e0253b9293b9)
![image](https://github.com/user-attachments/assets/8d91a57c-928f-4b40-866d-c12942f9ba90)

**Comment by sfc-gh-jreini** [comment]
Hi @cwitt2013 -

Unless the role has the `READ SESSION ON ACCOUNT` privilege, Streamlit nulls out `CURRENT_USER` (in addition to a few others) which is leading to this issue. You can solve it by doing either of the following:

```
USE ROLE ACCOUNTADMIN;
GRANT READ SESSION ON ACCOUNT TO ROLE streamlit_owner_role;
```

**Comment by cwitt2013** [comment]
Thank you @sfc-gh-jreini! That solved the issue. Do you have any documentation on the rights needed on Snowflake to run Trulens?

**Comment by sfc-gh-jreini** [comment]
There are not blanket privileges needed to run TruLens on Snowflake - but happy to help if you run into any other issues.
