### ISSUE TITLE
[BUG] Issue using TruLlama and llama-index

### ISSUE THREAD

**Issue by paul-gleeson** [truera/trulens#1631]
**Bug Description**
This is the same issue as described in this issue[https://github.com/truera/trulens/issues/1278] but I have been unable to solve it following the same instructions. I am unable to use TruLlama with Llama Index. 

![image](https://github.com/user-attachments/assets/12f961e6-db2a-4222-8f59-74b9c50e3a75)

**To Reproduce**
Assuming query engine & feedback functions are created elsewhere in the code:
```
tru_query_engine_recorder = TruLlama(
    query_engine,
    app_name="LlamaIndex_App",
    app_version="base",
    feedbacks=[f_pii_detection_input, f_pii_detection_output, f_positive_sentiment, f_toxicity],
)
```

**Expected behavior**
I am following the instructions in the previous issue answer but unable to get my pipeline working so i can use the feedback functions. 

**Environment:**

- windows
- python 3.10
- trulens==1.1.0 but also had the latest version and failed with that
- !pip install "llama-index>=v0.9.14.post3" but also tried with v1.2.0
- !pip install --upgrade trulens_eval==0.31.0

**Comment by sfc-gh-pmardziel** [comment]
Hi; a few things: can you uninstall trulens_eval and list all trulens packages with this:

```python
! pip uninstall -y trulens_eval
! pip install -U trulens-apps-llamaindex
! pip list | grep trulens
```

**Comment by paul-gleeson** [comment]
Ok I've followed your instructions - I'm now having trouble importing TruLlama from trulens.apps.llamaindex. I get the following error when running 
`from trulens.apps.llamaindex import TruLlama`

![image](https://github.com/user-attachments/assets/c07be844-b069-49d2-9d5e-5870bcf002cd)

My pip list is: 
```
trulens                                   1.1.0
trulens-apps-langchain                    1.0.3
trulens-apps-llamaindex                   1.2.4
trulens-core                              1.0.2
trulens-dashboard                         1.0.2
trulens-feedback                          1.0.2
trulens-providers-huggingface             1.0.2
trulens-providers-litellm                 1.0.2
```

**Comment by sfc-gh-jreini** [comment]
@paul-gleeson can you try in a fresh conda environment?

```bash
conda create -n trullamatest python=3.10
conda activate trullamatest
pip install trulens-apps-llamaindex
```

Then in python, the following should run without error:

```python
from trulens.apps.llamaindex import TruLlama
```
