### ISSUE TITLE
[FEAT] how can I use LLM from huggingface as the provider of the Trulens feedback?

### ISSUE THREAD

**Issue by Anchang8** [truera/trulens#1651]
I want to use the local model downloaded from Hugging Face as the provider of Trulens feedback for the RAG Evaluation project. If this feature is already available, how can I use it?
Thank you.

**Comment by sfc-gh-jreini** [comment]
Hi @Anchang8 - we don't currently have this feature through models running locally from Hugggingface, but we can run local LLMs as feedback providers using Ollama (via LiteLLM) if that would meet your needs.

Here's an example notebook:

[Ollama Quickstart](https://www.trulens.org/cookbook/models/local_and_OSS_models/ollama_quickstart/)

**Comment by sfc-gh-jreini** [comment]
@Anchang8 have you had a chance to give this a try?
