### ISSUE TITLE
trulens_eval.feedback.OpenAI with Azure

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [truera/trulens#233]
Hi there 👋 

I am using from `trulens_eval.feedback.OpenAI` but I need to pass extra args to use with azure, I don't understand the usage of  `OpenAIEndpoint` since I cannot see extra args to setup openai, usually you can do something like

```python
openai.api_type = "azure"
openai.api_base = os.getenv("OPENAI_API_BASE")
openai.api_version = "2023-03-15-preview"
openai.api_key = os.getenv("OPENAI_API_KEY")
```

Not sure how to do it with trulens

Thanks a lot

Cheers,

Fra

**Comment by shayaks** [comment]
Hi Fra,
We're looking into how to set Azure parameters in the openai API. We should be able to expose it in the OpenAI class soon.

**Comment by FrancescoSaverioZuppichini** [comment]
I've made a PR #242

**Comment by rshih32** [comment]
merged, this should make the next release (in a day or so)
