### ISSUE TITLE
[Bug] Selector `GetItems` crashes with `AttributeError`

### ISSUE THREAD

**Issue by lariel-fernandes** [truera/trulens#334]
### How to reproduce:
```python
from trulens_eval import Select

selector = Select.RecordCalls._call.args.inputs[["key1", "key2"]]

repr(selector)
```
Output:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../.venv/lib/python3.9/site-packages/trulens_eval/util.py", line 951, in __repr__
    return "JSONPath()" + ("".join(map(repr, self.path)))
  File ".../.venv/lib/python3.9/site-packages/trulens_eval/util.py", line 926, in __repr__
    return f"[{','.join(self.indices)}]"
AttributeError: 'GetItems' object has no attribute 'indices'
```

Then obviously this crashes any Feedback that uses this selector

### Suggested fix
On [util.py](https://github.com/truera/trulens/blob/e85e8f18763f38790e5964d2a77e785416f09647/trulens_eval/trulens_eval/util.py#L926)
```python
    def __repr__(self):
        return f"[{','.join(self.items)}]"
```

**Comment by joshreini1** [comment]
Thanks @lariel-fernandes for finding, the easy repro and suggested fix! Was able to repro and fix with your suggestion.

**Comment by joshreini1** [comment]
That is the standard procedure 😀, feel free to fork and PR in the future!

I just merged this change, so you can expect it in the next release, 0.8.0, or build from main if you want it sooner!
