### ISSUE TITLE
Feedback function on Groundedness did not work with AzureOpenAI

### ISSUE THREAD

**Issue by tarynduong** [truera/trulens#360]
The summarize_provider is default to OpenAI, which prevents from instantiating ChatCompletion with AzureOpenAI.

![image](https://github.com/truera/trulens/assets/85856280/659cf885-b1df-434c-96f2-55f8928e56a4)

**Comment by joshreini1** [comment]
Hi @tarynduong - I have an open PR to fix this issue [here](https://github.com/truera/trulens/pull/369). Please take a look to see if this solution works for your case.

Thanks!
