### ISSUE TITLE
Add multiple tags using a list or multiple columns called tag1, tag2 to TruChain

### ISSUE THREAD

**Issue by harkrish1** [truera/trulens#365]
This will be helpful if we want to track user ID, and session ID, customer ID and other related information in the session.

**Comment by joshreini1** [comment]
Hey @harkrish1 !

Right now there's a few options:
For app-level tags, you can pass the `metadata` arg when you wrap your application, like:
```
tru_query_engine = TruLlama(query_engine,
                    metadata={
                        'embed_model':embed_model_name,
                        'top_k':top_k,
                        'chunk_size':chunk_size
                        })
```

Or for record-level information you can add the `record_metadata` arg to your application call like so:
```
metadata = dict(tag1="prototype", field2="segment A")
tru_chain(input_prompt, record_metadata = metadata)
```

Do either of these approaches work for you?

**Comment by joshreini1** [comment]
Hey @harkrish1 !

In 0.11.0 we added record-level metadata. You can add the `record_metadata` arg to your application call like so:
```
metadata = dict(user_id="u_xyz", session_id="session_abc", customer_id="cust_123")
tru_chain(input_prompt, record_metadata = metadata)
```

Does this work for your you?
