### ISSUE TITLE
Changing the input of `agreement_measure` returns nan

### ISSUE THREAD

**Issue by Mymoza** [truera/trulens#368]
**Usecase:** When changing the input to a custom input, `agreement_measure` returns nan. 

If one changes the input like so: 

```python
f_agreement_measure = Feedback(GroundTruthAgreement(answers, azure).agreement_measure).on(
                Select.Record.calls[0].rets.query).on(
                Select.Record.main_output["answer"]
)
```

You can see that in `agreement_measure_calls`, the `ret` and `meta` are empty because it wasn't able to find the input in the dictionary:

```
[{'args': {'prompt': 'Prompt 1 Modified', 'response': "response 1"}, 'ret': nan, 'meta': {}}]
```

From what I've understood so far, it's because in `GroundTruthAgreement` and `_find_response()`, it is searching for the original query `Prompt 1`, like in `Select.Record.main_input`. Instead, it is searching for a query containing `Prompt 1 Modified`, contained in `Select.Record.calls[0].rets.query`, but can't find it: 

```
self.ground_truth = [{'query': 'Prompt 1', 'response': 'response 1'}]
```

Therefore, it returns nan.

**Comment by piotrm0** [comment]
Hi; what is `answers` populated with in your example?

**Comment by Mymoza** [comment]
Hi! `answers = []`, and I don't have them at the moment that I call the `Feedback` function as it is changed in the chain, so I don't see how I could populate it at that stage.... (?)

**Comment by shayaks** [comment]
@Mymoza that's the intended behavior. Essentially if there isn't a ground truth entry, the output is undefined. It also doesn't get picked up by the statistics on the leaderboard.
