### ISSUE TITLE
[Bug] Dashboard breaks with `llama-index>0.7.23`

### ISSUE THREAD

**Issue by lariel-fernandes** [truera/trulens#385]
**Affects releases: 0.9.0**

## Issue
Dashboard breaks if I my Python environment has `llama-index 0.7.24.post1` or later.

Not sure if it's an issue with the new `llama-index` releases or a compatibility issue between that and trulens-eval.

I can only get it to work by setting `llama-index>=0.7.16,<=0.7.23` in `requirements.txt` or `pyproject.toml`

## Reproduce
Update to `llama-index=0.7.24.post1` or later (up to `0.8.2`), then run `Tru().start_dashboard()` and browse to the dashboard.

See dashboard log here: [log.txt](https://github.com/truera/trulens/files/12359341/log.txt)

## Suggestion
A temporary workaround would be pinning the `llama-index` version to `0.7.23` in `requirements.txt` and `setup.py`.

But users of trulens-eval would miss on any future `llama-index` updates while the issue lasts.

**Comment by piotrm0** [comment]
Fix in next release. Temporary workaround is discussed here: https://github.com/jerryjliu/llama_index/issues/7244 .

**Comment by joshreini1** [comment]
Released in 0.10.0
