### ISSUE TITLE
[Bug] Missing Package and Unicode Encode Error

### ISSUE THREAD

**Issue by tarynduong** [truera/trulens#396]
Hello, you forgot to import os :D 
![image](https://github.com/truera/trulens/assets/85856280/4b8a2594-1bdf-4a3c-9478-025d3f90ceef)
And it seems that these symbols below only work with Streamlit. The Azure Function libs do not support encoding these unicode characters. When I replace them with nothing, my app works. Could you consider removing them? 
<img width="402" alt="Capture" src="https://github.com/truera/trulens/assets/85856280/a6b429a3-e414-4606-b42f-6355579d51c4">

**Comment by shayaks** [comment]
@tarynduong Thanks for the feedback! Could you share a bit more about how you're using Azure Functions and where you're running into errors?

**Comment by lkNGAT** [comment]
Hello,
I have the same problem on a windows machine runnning python 3.10
```
Tru().run_dashboard()
File "C:\Users\lkNGAT\project\venv\lib\site-packages\trulens_eval\tru.py", line 117, in __init__
print(
File "C:\Users\lkNGAT\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f991' in position 0: character maps to <undefined>
```

**Comment by piotrm0** [comment]
There is some discussion here: https://stackoverflow.com/questions/14630288/unicodeencodeerror-charmap-codec-cant-encode-character-maps-to-undefined

@lkNGAT @tarynduong Can you put this in your code before you import or use trulens and let us know if the issue persists:
```python
if sys.stdout.encoding != 'cp850':
  sys.stdout = codecs.getwriter('cp850')(sys.stdout.buffer, 'strict')
if sys.stderr.encoding != 'cp850':
  sys.stderr = codecs.getwriter('cp850')(sys.stderr.buffer, 'strict')
```
