### ISSUE TITLE
Using it with out the Sqllite db

### ISSUE THREAD

**Issue by ricoyudog** [truera/trulens#422]
Hi Teams
The record tracking function is look great！
I would like to ask is it possible to use it with out running a db, I mainly want to use it to get the tracking record for each time of my call.

Thank you very much

**Comment by rshih32** [comment]
Hi @ricoyudog ,
Yes you can! 

Each tru wrapper has a *_with_record method that has this information populated.

for example: https://www.trulens.org/trulens_eval/api/truchain/
```
response = my_llm_app(query)

from trulens_eval import TruChain
# f_lang_match, f_qa_relevance, f_qs_relevance are feedback functions
truchain = TruChain(
    my_llm_app,
    app_id='Chain1_ChatApplication',
    feedbacks=[f_lang_match, f_qa_relevance, f_qs_relevance])
)
response, tru_record = truchain.call_with_record("What is langchain?")

latency = tru_record.perf.end_time - tru_record.perf.start_time
```

**Comment by ricoyudog** [comment]
> 

But it seems like when my pipeline is finished, the terminal is still not close

**Comment by rshih32** [comment]
Are you running the dashboard? That kicks off a long living thread that will prevent terminal closing. You can either stop the dashboard with tru.stop_dashboard() or not run the dashboard

Otherwise let me know if I'm not on the right path in understanding your question
