### ISSUE TITLE
"Display full app json" always shows data for first row on the Dashboard

### ISSUE THREAD

**Issue by molntamas** [truera/trulens#423]
If I open trulens-eval dashboard evaluations -> http://localhost:8501/Evaluations
And have mulitple records,
when I select a different record then the first one in the row,
still the first record's data is shown in the bottom part "Display full app json".
Expected behaviour: the data for the other row should be displayed.

My code to run trulens:
```
truchain = TruChain(chain, app_id="app_id", tags="my tag)
await truchain.acall_with_record(variables)

```
trulens-eval version: 0.11.0

**Comment by rshih32** [comment]
An app json is a specific state of the wrapped app. It is keyed by the app_id. It's likely that if you are expecting differences in the app json, that its probably picking up only 1 version based on the app_id. Can you validate that if you are expecting app json changes, and the app_id is changed, that the json gets updated?

If that is validated; we can think of having a hash key based upon the json value to make sure we pick up changes.
