### ISSUE TITLE
No notebooks for NLP and time-series RNNs .

### ISSUE THREAD

**Issue by DevavratSinghBisht** [truera/trulens#43]
The notebooks directory contains notebooks named [intro_demo_pytorch.ipynb](https://github.com/truera/trulens/blob/master/notebooks/intro_demo_pytorch.ipynb) and [intro_demo_tf2_keras.ipynb](https://github.com/truera/trulens/blob/master/notebooks/intro_demo_tf2_keras.ipynb) , these notebooks show how trulens can be used for visualizing and explaining an image classification model. I request similar notebooks for NLP and time-series RNNs so that users can easily get started with them.
Thankyou!

**Comment by piotrm0** [comment]
Recently added was https://github.com/truera/trulens/blob/master/notebooks/nlp_demo_pytorch.ipynb .
