### ISSUE TITLE
Multiple tags for a record?

### ISSUE THREAD

**Issue by molntamas** [truera/trulens#431]
I was wondering if it is supported to add multiple tags for a record.

Example code from the documentation for adding tags:
https://www.trulens.org/trulens_eval/langchain_quickstart/#instrument-chain-for-logging-with-trulens
```
truchain = TruChain(chain,
    app_id='Chain1_ChatApplication',
    feedbacks=[f_lang_match],
    tags = "prototype")
```

What if I wanted to add one more tag, e.g. 
`tags = ["tag1","tag2"]`

Is something like this supported?
Currently I get an error, that a single string is expected.

**Comment by joshreini1** [comment]
Hey @molntamas !

Right now there's a few options:
For app-level tags, you can pass the `metadata` arg when you wrap your application, like:
```
tru_query_engine = TruLlama(query_engine,
                    metadata={
                        'embed_model':embed_model_name,
                        'top_k':top_k,
                        'chunk_size':chunk_size
                        })
```

Or for record-level information you can add the `record_metadata` arg to your application call like so:
```
metadata = dict(tag1="prototype", field2="segment A")
tru_chain(input_prompt, record_metadata = metadata)
```

Do either of these approaches work for you?
