### ISSUE TITLE
Quickstart example not actually logging

### ISSUE THREAD

**Issue by mdagost** [truera/trulens#454]
The change to use a context manager doesn't actually log anything:

```
with tru_llm_standalone as recording:
    llm_standalone(prompt_input)
```

If instead I change that to

```
tru_llm_standalone.call_with_record(prompt_input)
```

I see records logged.

**Comment by rshih32** [comment]
Hi @mdagost , we are in the middle of changing the quickstarts and documentation. Hopefully will be out today.

Please try

```
with tru_llm_standalone as recording:
    llm_standalone.app(prompt_input)
```

The context manager does require a class to be logged; so we provide it via the `app` attribute

**Comment by rshih32** [comment]
This was deployed yesterday:

https://colab.research.google.com/github/truera/trulens/blob/releases/rc-trulens-eval-0.13.0/trulens_eval/examples/colab/quickstarts/text2text_quickstart_colab.ipynb

**Comment by piotrm0** [comment]
Note that in the solution above `app` is not `tru_llm_standalone` but rather an instance of a class that wraps that callable.
