### ISSUE TITLE
Log the production data into Bigquery and retrieve the analysis based on it

### ISSUE THREAD

**Issue by noshad-vida** [truera/trulens#497]
Hello,
I'm wondering how we can log the production data into Bigquery database and then retrieve them later to analyze the results.

**Comment by joshreini1** [comment]
Hi @noshad-vida !

We have integration with SQLAlchemy that allows you to do this.

Check out our docs on using SQLAlchemy with TruLens: https://www.trulens.org/trulens_eval/where_to_log/

and this article on using BigQuery with SQLAlchemy:
https://googleapis.dev/python/pybigquery/0.7.0/

**Comment by noshad-vida** [comment]
@joshreini1 thanks for your response. I just don't find a sample code to display the evaluation dashboard using the logged data.

**Comment by joshreini1** [comment]
Once you initialed Tru with bigquery:

from trulens_eval import Tru
tru = Tru(database_url=“your bigquery db url/auth here")

All logging will be done there, and tru.run_dashboard() will launch from the logs in that db. Let me know if you run into any snags doing this as you’re likely the first setting this up in BigQuery!

**Comment by joshreini1** [comment]
@noshad-vida were you able to use this?
