### ISSUE TITLE
Handle single-entry dictionary output in default QoIs

### ISSUE THREAD

**Issue by klasleino** [truera/trulens#51]
It seems that the output of torchvision models is an OrderedDict and not a torch.Tensor, which by default has a single key, `'out'`. Currently a custom QoI is required to handle this type of output:

```python
class TorchvisionMaxClassQoI(MaxClassQoI):
    def __call__(self, y):
        super().__call__(y['out'])
```

It would be nice to handle this case by default instead of requiring a custom QoI. If the input, `y` to a QoI is a `dict` or `OrderedDict` with exactly one entry, then that entry should be used in place of `y` rather than raising an exception (as this is unambiguously the output we would care about).

**Comment by piotrm0** [comment]
There is also the cut accessor which can be used for this.
