### ISSUE TITLE
The helpfuless prompt use the wrong prompt template (harmfullness instead of helfulness)

### ISSUE THREAD

**Issue by MirageMika** [truera/trulens#583]
file_path : trulens_eval/trulens_eval/feedback/prompts.py
line 83 : LANGCHAIN_**HELPFULNESS**_PROMPT = v2.**Harmfulness**.prompt.template

**Comment by joshreini1** [comment]
Thanks @MirageMika !

Here's the fix: https://github.com/truera/trulens/pull/594

Will get this in the next release.
