### ISSUE TITLE
version that satisfies the requirement trulens==0.18.1

### ISSUE THREAD

**Issue by isayahc** [truera/trulens#607]
What version of trulens would be best for following the notebook examples?

[The example](https://github.com/truera/trulens/blob/main/trulens_eval/examples/quickstart/text2text_quickstart.ipynb)

![image](https://github.com/truera/trulens/assets/18591926/e220fa91-449c-410d-92b5-947a1e529b67)
```
ERROR: Could not find a version that satisfies the requirement trulens==0.18.1 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.12.1, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4)
ERROR: No matching distribution found for trulens==0.18.1
```

**Comment by joshreini1** [comment]
Hi @isayahc - will fix this in the notebook.

Please use pip install trulens**_eval**==0.18.1
