### ISSUE TITLE
upgrade to typing-extensions 4.8.0

### ISSUE THREAD

**Issue by kocsszi** [truera/trulens#613]
Using fastapi later versions rely on 4.8.0, just one example, many other install inconvenience could be avoided.

Could you please use the later versions of typing-extensions?

**Comment by piotrm0** [comment]
The version of `typing-extension` was unpinned recently in our package requirements so you should be able to use 4.8.0 with the next release of trulens_eval.

**Comment by kocsszi** [comment]
@piotrm0 thank you that is great news. can you estimate when next release would be?

**Comment by joshreini1** [comment]
Hey @kocsszi - we will release either today or early next week.

If you don't want to wait, you can also clone and install from the repository:

`cd trulens/trulens_eval`
`pip install -e .`

Cheers!
