### ISSUE TITLE
AzureOpenAI feedback provider: 'deployment_id' error

### ISSUE THREAD

**Issue by FernandoBenayas** [truera/trulens#620]
Hi all!

I'm using a LLM from Azure OpenAI in order to implement a basic groundedness+question/statement+question/answer relevance use case ([this one](https://github.com/truera/trulens/blob/a9717080c3218a51dfc299bb5e8f8c552e6987ab/trulens_eval/examples/expositional/models/azure_openai.ipynb#L178)), and I'm getting an error which I believe is related to the way the **AzureOpenAI class** is implemented in **trulens_eval.feedback.provider.openai**.

The error message is:

> openai request failed <class 'TypeError'>=Completions.create() got an unexpected keyword argument 'deployment_id'. Retries remaining=3.

(and further retries)

Which makes sense, since this is how I'm creating the LLM provider:
`from trulens_eval.feedback.provider.openai import AzureOpenAI`
`openai_provider = feedback.AzureOpenAI(
    deployment_id="<azure deployment name>",
    model_engine="gpt-35-turbo"
)`

I can't take the _deployment_id_ argument out, since it is enforced [by the definition of the AzureOpenAI class](https://github.com/truera/trulens/blob/trulens-eval-0.18.0/trulens_eval/trulens_eval/feedback/provider/openai.py#L380).

But, AzureOpenAI [is a subclass of OpenAI](https://github.com/truera/trulens/blob/trulens-eval-0.18.0/trulens_eval/trulens_eval/feedback/provider/openai.py#L380), which uses OpenAI's _client.chat.completions.create_ function, which doesn't expect any _deployment_id_ argument ([it seems like the _model_ argument is used to specifiy Azure's deployment_name](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/chatgpt?tabs=python-new&pivots=programming-language-chat-completions)).

What do you guys/gals think? Am I doing something wrong? Or this is a bug in trulens' code?

**Comment by joshreini1** [comment]
Thanks for reporting @FernandoBenayas ! Taking a look

**Comment by Ethan-Otto** [comment]
I have the same error

**Comment by haolxx** [comment]
same error

**Comment by joshreini1** [comment]
@daniel-huang-1230 has a fix that will be released today. thanks for the patience all!

**Comment by daniel-huang-1230** [comment]
https://github.com/truera/trulens/pull/640

Thanks for the contribution from [schmidtseb](https://github.com/schmidtseb)!

**Comment by lorenzobalzani** [comment]
It works as expected. Thanks guys ;)
