### ISSUE TITLE
Can this tool be used locally without external services?

### ISSUE THREAD

**Issue by se-kon** [truera/trulens#630]
Came due to the course on deeplearning.ai.

**Comment by se-kon** [comment]
Thanks!

Maybe I stated it incorrectly.

I would like to use Azure OpenAI, but I was referring to your logging services.

**Comment by joshreini1** [comment]
Hey @se-kon - logging is all local!

See for reference: https://www.trulens.org/trulens_eval/where_to_log/

**Comment by se-kon** [comment]
thanks!
