### ISSUE TITLE
trulens-eval meets hallucinations detection and reduction

### ISSUE THREAD

**Issue by snassimr** [truera/trulens#635]
Hi ,

I wonder what metric is proposed to measure hallucination rate . There are many definitions for this metric . I'd like to know what the vision of package creators and reasonable explanation. 

Thanks,
Nissim

**Comment by joshreini1** [comment]
Hey @snassimr !

In RAG contexts, we consider the RAG Triad of context relevance, groundedness and answer relevance to hold the key for measuring hallucination.

Would recommend checking out this section of the docs: https://www.trulens.org/trulens_eval/core_concepts_rag_triad/

**Comment by joshreini1** [comment]
Let us know if you have further questions - thanks!

**Comment by snassimr** [comment]
Can I use  Answer Relevance * Context Relevance * Groundedness as sort of goodness of fit  similar to accuracy/auc in Binary classification problem ?

**Comment by joshreini1** [comment]
If you want just one metric I think that’s reasonable. I’d suggest you gain a lot more power in discovering failure modes/possible areas of improvement if you use them separately however.
