### ISSUE TITLE
tru.run_dashboard() raised WinError, trulens_eval versions '0.18.1', '0.18.2' 

### ISSUE THREAD

**Issue by haolxx** [truera/trulens#642]
>>> from trulens_eval import Feedback, OpenAI, Tru, TruLlama, Select, OpenAI as fOpenAI
>>> tru = Tru()
🦑 Tru initialized with db url sqlite:///default.sqlite .
🛑 Secret keys may be written to the database. See the `database_redact_keys` option of `Tru` to prevent this.

>>> tru.run_dashboard()
Starting dashboard ...
Config file already exists. Skipping writing process.
Credentials file already exists. Skipping writing process.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "xxxxxxxxxxxx\anaconda3\envs\GenAI_Stable\lib\site-packages\trulens_eval\tru.py", line 543, in run_dashboard
    proc = subprocess.Popen(
  File "xxxxxxxxxxxx\anaconda3\envs\GenAI_Stable\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "xxxxxxxxx\anaconda3\envs\GenAI_Stable\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
**FileNotFoundError: [WinError 2] The system cannot find the file specified**

**Comment by joshreini1** [comment]
Hey @haolxx !

What environment are you running this in? Can you share more details so we can reproduce?

**Comment by haolxx** [comment]
> Hey @haolxx !
> 
> What environment are you running this in? Can you share more details so we can reproduce?

I'm using the code in a anaconda environment with python 3.10.13. thx

**Comment by joshreini1** [comment]
Assuming you're also on Windows based on the error?

**Comment by haolxx** [comment]
> Assuming you're also on Windows based on the error?

Correct

**Comment by joshreini1** [comment]
Having trouble reproducing this. Is this a VM? Do you see the logging db (default.sqlite) in your local directory?

**Comment by haolxx** [comment]
> Having trouble reproducing this. Is this a VM? Do you see the logging db (default.sqlite) in your local directory?

not a VM - just an anaconda environment in my local machine. Yes, I see those 2 lines of code created the default.sqlite file and the .streamlit folder in my working directory.  .streamlit folder has 2 files: config and credentials.

**Comment by haolxx** [comment]
I switched back to python 3.8 and it worked now... not sure why it failed for python 3.10.13...

**Comment by joshreini1** [comment]
Good to know - thanks! Will continue to look into why it's sometimes failing for 3.10.13
