### ISSUE TITLE
get_records_and_feedback function doesn't return the `relevance` key

### ISSUE THREAD

**Issue by artem-seraf** [truera/trulens#643]
I'm running the following code to estimate answer relevance.

```
for item in qa_pairs:
    with tru_recorder as recording:
        question = item['question']
        tru_recorder.app(question)

records = self._tru.get_records_and_feedback([])[0]

return records['relevance'].tolist()
```

When I'm trying to retrieve the relevance score from the output, I'm getting `KeyError: 'relevance'`. However, if I make some delay before the return statement, the key `relevance` is presented. This code is executed within an async function. It seems that there is some issue with background update of the results.

**Comment by joshreini1** [comment]
Hi @artem-seraf - the first time a feedback function is used, it's feedback column wouldn't be added to the records db until the feedback is generated. Does that make sense?

Does this cause any issues for you downstream?

**Comment by artem-seraf** [comment]
Hi @joshreini1 
Thanks for your reply. Such a behaviour causes an error in my app because I'm trying to score question/answer pairs and write scores to my local DB. Thus, I need a way to ensure that all feedbacks are generated before the work with the DB.
Now it seems that I managed how to deal with that in a hacky way. I revealed that the `recording` object contains `Future` objects that correspond to the result of the execution of the feedback. Thus, I'm trying to extract these `Future` objects and wait for the end of their execution.

```
all_future_objects = []
for item in qa_pairs:
	with tru_recorder as recording:
		question = item['question']
		tru_recorder.app(question)
		
		# Extract all Future objects that correspond to the execution results of a feedback
		all_future_objects.append(recording.records[0].feedback_results[0])

# Wait for the end of the execution of all feedbacks
concurrent.futures.wait(all_future_objects)
```

**Comment by piotrm0** [comment]
Hi @artem-seraf ; another way to do this is to use the "WITH_APP" FeedbackMode (a parameter to TruChain/TruLamma/*) which will configure it to block on your app invocation until feedbacks are computed (effectively the same thing you are doing now with waiting for the futures). Your solution is more efficient though as it allows them to operate in parallel.

**Comment by artem-seraf** [comment]
Hi @piotrm0 
Thanks for this tip! Actually, the previous code wasn't working in all cases (sometimes, I was still getting the error realted with the key absence). I assume that there are more async operations except futures that are involved into the retrieval of updated records (maybe it is connected with Sqlite). The following code snippet seems to work in a stable way.

```
all_future_objects = []
for item in qa_pairs:
	with tru_recorder as recording:
		question = item['question']
		tru_recorder.app(question)
		all_future_objects.append(recording.records[0].feedback_results[0])

# Wait for all Future objects and retrieve scores directly from the responses
scores = []
for f in as_completed(all_future_objects):
	response = f.result()
	scores.append(response[1].result)

```
