### ISSUE TITLE
Langchain provider for all types of LLMs

### ISSUE THREAD

**Issue by Nvillaluenga** [truera/trulens#645]
I'm trying to implement feedback functions with google endpoints in vertex AI the same way that works for OpenAI. 

I do not want to implement a provider that is solely for google, I would like to implement it for langchain directly but reusing the structure provided by [LLMProvider](https://github.com/truera/trulens/blob/main/trulens_eval/trulens_eval/feedback/provider/base.py#L30) (which is not exposed by the way)

In this way we are not dependent of the particular LLMs implementation but use langchain as a middleware.

Is this something that is in the radar or do you think will be a good addition?

**Comment by joshreini1** [comment]
Hey @Nvillaluenga ! This would be really useful, @shayaks and I were discussing that earlier this afternoon.

**Comment by Nvillaluenga** [comment]
Great will try to implement this over the weekend!

**Comment by Nvillaluenga** [comment]
Hey there, here is my [PR](https://github.com/truera/trulens/pull/664) I tried to keep it as simple as possible, let me know what do you think.

PS: I'm thinking on adding some unit test later in the week.

**Comment by joshreini1** [comment]
Merged! Will be released on 0.19
