### ISSUE TITLE
Supporting harmless metrics

### ISSUE THREAD

**Issue by snassimr** [truera/trulens#655]
Hi , 

I wonder if trulens supports any harmless evaluations metrics ?

I see a reference to this https://github.com/truera/trulens/blob/main/core_concepts_honest_harmless_helpful_evals.md

but the document doesn't exists

**Comment by daniel-huang-1230** [comment]
hey there!

Yes there are a couple of built-in feedback functions that can be used to evaluate harmlessness 

please see https://github.com/truera/trulens/tree/main/trulens_eval/examples/expositional/use_cases/iterate_on_rag and let us know if these are helpful.

P.S. notebooks are a bit outdated but we are iterating fast on updating the examples this week so stay tuned! :)
