### ISSUE TITLE
Unit test should not call LLMs

### ISSUE THREAD

**Issue by Nvillaluenga** [truera/trulens#665]
Unit test should not have dependencies with LLMs.

API calls should be mocked, to ensure the test are in fact unitary.

Furthermore this is producing inconsistent result in the pipelines due to fails in the api calls (For example due to quota exceeded with OpenAI)

That beeing said I think **We need to mock LLMs calls**

**Comment by joshreini1** [comment]
Hey @Nvillaluenga ! Just checking to see if you still planned to take this on?
