### ISSUE TITLE
Integration with other vectorDBs

### ISSUE THREAD

**Issue by PrashantDixit0** [truera/trulens#667]
@joshreini1 
Are you open to Integrate with other VectorDBs for giving flexibility to user to use TruLens with any vectorDB of their choice?

I can work on integrating with ChromaDB and LanceDB for scalibility.
Please let me know, What are your thoughts on this.

**Comment by joshreini1** [comment]
Hey @PrashantDixit0 ! Because we wrap the application itself, it’s agnostic to the vector db being used (no need to write integration code).

However if you want to add examples for other vector dbs, that’d be great!
