### ISSUE TITLE
Does TruLens work with Local LLM using Langchain without OpenAI Key?

### ISSUE THREAD

**Issue by navinchandrac** [truera/trulens#674]
Does TruLens work with Local LLM using Langchain without OpenAI Key? (Example for Local LLM: https://colab.research.google.com/drive/1XVjur9cdYLhxe6mrQwQUlWIm4VJmiYlu?usp=sharing#scrollTo=wJ7k5mYXj0vG)

Getting below error while using TruLens with Local LLM using Langchain for above example

**_ImportError: cannot import name 'LLM' from 'llama_index.llms.base' (/usr/local/lib/python3.10/dist-packages/llama_index/llms/base.py)_**

Also which LLM used by TruLens (as internal) for to get expected feedback parameters result comparison with LLM App actual feedback result?

**Comment by piotrm0** [comment]
Hi; this may be due to recent changes in llama_index, can you update both the trulens_eval package and llama_index package?

**Comment by joshreini1** [comment]
Hey @navinchandrac ! The error message you posted about above is fixed/released, however it's unreleated to running feedback functions with a Local LLM. Can you post more info on that if you're still struggling?

**Comment by joshreini1** [comment]
Hey again @navinchandrac ! Just added a new example of using ollama to run feedback functions locally in this [PR](https://github.com/truera/trulens/pull/703). Feel free to check it out!

Closing this issue for now. Please create a new one or re-open if you run into new issues
