### ISSUE TITLE
ImportError: cannot import name 'LLM' from 'llama_index.llms.base'

### ISSUE THREAD

**Issue by wenhao89** [truera/trulens#675]
I encounted "**ImportError**: cannot import name 'LLM' from 'llama_index.llms.base'" when running the following code:

`from trulens_eval import Tru`

I investigated 'llama_index.llms.base' and realised that the 'LLM' class had been renamed as 'BaseLLM'. I adjusted the source code and managed to get the code to work, but thought to report the issue here as well.

**Comment by joshreini1** [comment]
Thanks for reporting @wenhao89 ! This is already patched in main and will be released in 0.19 today.

**Comment by joshreini1** [comment]
Following up @wenhao89  - this change is released! Please upgrade to trulens_eval==0.19.1. Thanks!
