### ISSUE TITLE
Is there anyway to specify streamlit  server.port and server.address properties when running the tru.run_dashboard()

### ISSUE THREAD

**Issue by VikramAIS** [truera/trulens#676]
Hi Team,

I am planning to deploy the Trulens-Eval dashboard on Azure App Server. Please let me if any documentation or example available to deploy trulens-eval in azure app service.

If not, let me know is there any way to pass **server.port** and **server.address** to **run_dashboard** function call

**Comment by SanjuMLGeek** [comment]
I am also looking for the same capability

**Comment by piotrm0** [comment]
Hi, we added `port` and `address` arguments to `Tru.run_dashboard`. You can use it now from the github version or wait until next release.

**Comment by joshreini1** [comment]
Hey @VikramAIS and @SanjuMLGeek ! This is released in trulens_eval==0.19.2. Please upgrade to get this feature, thanks!
