### ISSUE TITLE
Error while importing Tru from trulens_eval

### ISSUE THREAD

**Issue by SanjuMLGeek** [truera/trulens#678]
Hello,

I am running below code from Sagemaker Jupyter notebook and somehow when I run this code it throw error as attached. I checked the version of llama_index and its the latest 0.9.15 and also using latest versions of trulens  and trulens_eval. 
If I import LLM from llama_index.llm.base independently, I don't see any error.

`from trulens_eval import Tru`

<img width="1115" alt="Screenshot 2023-12-14 at 3 00 32 PM" src="https://github.com/truera/trulens/assets/43816307/98b89e9a-9507-48b9-a48d-170ecc78115d">

**Comment by victormimo** [comment]
Same here

**Comment by michaelromagne** [comment]
Hi @SanjuMLGeek  @victormimo  ! I had the same problem and will propose a MR in a few minutes to fix this

**Comment by michaelromagne** [comment]
Actually the Trulens team already fixed it 2 days ago : https://github.com/truera/trulens/pull/671

So you just have to update your trulens imports locally until they release version 0.18.4 and update the install in their tutorials

@joshreini1 you contacted me on Twitter and that was my problem :)

**Comment by joshreini1** [comment]
Thanks Michael! Glad to hear you found the fix:)

**Comment by joshreini1** [comment]
Following up @michaelromagne @victormimo @SanjuMLGeek - this change is released! Please upgrade to trulens_eval==0.19.1. Thanks!

**Comment by SanjuMLGeek** [comment]
Thank you. I have tested it and working good now. Need help on issue [# 676](https://github.com/truera/trulens/issues/676) now..!!
