### ISSUE TITLE
Any implementation to stay under OpenAI rate limit for feedback functions?

### ISSUE THREAD

**Issue by chiffonng** [truera/trulens#687]
I'm running a RAG pipeline with `LlamaIndex` and evaluate it using 4 evaluations from `trulens` as below. The query engine from LlamaIndex always work independently, and I also tried to implement some exponential backoff to delay sending the request. However, it always fails after sending one or two metrics to OpenAI

```python
import time
from tenacity import retry, stop_after_attempt, wait_random_exponential
from trulens_eval import FeedbackMode


tru_recorder = TruLlama(
    query_engine,
    app_id="Test",
    feedbacks=[
        f_groundtruth,
        f_qa_relevance,
        f_qs_relevance,
        f_groundedness,
    ],
)


# Avoid rate limit issues through exponential backoff
@retry(
    stop=stop_after_attempt(3),
    wait=wait_random_exponential(multiplier=2, min=30, max=120),
)
def ask(question: str):
    with tru_recorder as recording:
        query_engine.query(question)


for q in honest_questions:
    ask(q)
```

The error is something like:
```
Groundendess per statement in source:   0%|          | 0/14 [00:00<?, ?it/s]openai request failed <class 'openai.RateLimitError'>=Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-3.5-turbo in organization org-pH2v2pPIHO0Gx1qW6X6RSpoO on requests per min (RPM): Limit 3, Used 3, Requested 1. Please try again in 20s. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing.', 'type': 'requests', 'param': None, 'code': 'rate_limit_exceeded'}}. Retries remaining=3.

[EXCLUDED BUT RETRIES]
Error calling wrapped function get_response.

[EXCLUDED BUT MORE RETRIES]

RateLimitError                            Traceback (most recent call last)

with tru_recorder as recording:
     query_engine.query(question)
...
     raise retry_exc from fut.exception()
     if self.wait:
     sleep = self.wait(retry_state)
     
RetryError: RetryError[<Future at 0x33159b690 state=finished raised RateLimitError>]
```

**Comment by piotrm0** [comment]
Hi; you can reuse the pacing scheme we use for the feedback functions. Here is an example:
```python
from trulens_eval import OpenAI
o = OpenAI()
o.endpoint.rpm = 3
while True:
    print(o.endpoint.pace_me())
    # Whatever follows will run at rpm of 3 max.
```

**Comment by chiffonng** [comment]
Thanks for quick response. I implemented your suggestion but only 2/15 questions in my test set went through the RAG triad of metrics in the best attempt.

I don't know if it's because I used the API when many other people were using it too.

**Comment by joshreini1** [comment]
Hey @chiffonng !

Can you try adding feedback_mode="with_app" to your app?

For example:

tru_recorder = TruLlama(
    query_engine,
    app_id="Test",
    feedbacks=[
        f_groundtruth,
        f_qa_relevance,
        f_qs_relevance,
        f_groundedness,
    ],
   feedback_mode="with_app"
)

**Comment by joshreini1** [comment]
@chiffonng please re-open if you are still experiencing this issue. Closing for now.

**Comment by zhongshuai-cao** [comment]
Is there a way to implement the token limit instead of request limit? As the question and answer can be long or short, the token based could be better.

**Comment by Sudhakar17** [comment]
@zhongshuai-cao 
I am facing the same token limit issues. Did you come up with any solution?

**Comment by sfc-gh-jreini** [comment]
TruLens 2.8 will add a `metric_max_workers` knob to the Run API that gives you direct control over evaluation concurrency:

```python
run.compute_metrics(metrics, metric_max_workers=1)  # sequential, avoids rate limits
```

By default it parallelizes across metrics and records, but setting `metric_max_workers=1` forces sequential execution to stay within rate limits. You can tune this to match your provider's RPM quota.

PR: https://github.com/truera/trulens/pull/2391
