### ISSUE TITLE
Getting error while while executing "tru.run_dashboard()" on Colab

### ISSUE THREAD

**Issue by navinchandrac** [truera/trulens#712]
Getting below error while executing **tru.run_dashboard()** code on **Colab**

**Error Message:** 

Starting dashboard ...
Config file already exists. Skipping writing process.
Credentials file already exists. Skipping writing process.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-45-4daf7c350606>](https://localhost:8080/#) in <cell line: 72>()
     70 #display(rec)
     71 
---> 72 tru.run_dashboard()

[/usr/local/lib/python3.10/dist-packages/trulens_eval/tru.py](https://localhost:8080/#) in run_dashboard(self, port, address, force, _dev)
    547 
    548         if Tru.dashboard_proc is not None:
--> 549             print("Dashboard already running at path:", Tru.dashboard_urls)
    550             return Tru.dashboard_proc
    551 

AttributeError: type object 'Tru' has no attribute 'dashboard_urls'

**Comment by piotrm0** [comment]
Hi; does this happen the first time tru().run_dashboard() is called? That is, can you check whether perhaps you are calling this twice, especially in close succession?

**Comment by navinchandrac** [comment]
Yes. Getting error while calling first time tru().run_dashboard() 

Please find the attached Colab file for your reference with code.

[Local_LLM_using_Langchain (4).zip](https://github.com/truera/trulens/files/13748226/Local_LLM_using_Langchain.4.zip)

**Comment by piotrm0** [comment]
Hi; there was an error introduced in last release that caused this issue. A fix is in the next release (or you can use the github version).

**Comment by joshreini1** [comment]
@navinchandrac - can you please retry with the latest release (0.20.0)?
