### ISSUE TITLE
Getting error when using AzureOpenAI for feedback functions

### ISSUE THREAD

**Issue by cedric-issel** [truera/trulens#715]
I am running the tutorial from here: https://www.trulens.org/trulens_eval/quickstart/#set-up-feedback-functions

Only difference: I use AzureOpenAI instead of OpenAI.

For the feedback functions I bind the openai client like this:
```python
from trulens_eval.feedback.provider.openai import AzureOpenAI as fAzureOpenAI

azopenai = fAzureOpenAI(
    api_key=os.getenv("AZURE_OPENAI_KEY"),
    azure_endpoint = os.getenv("AZURE_OPENAI_ENDPOINT"),
    api_version = os.getenv("AZURE_API_VERSION")
)
```

Once I run my evaluation questions through the app I get the following error:

Callback class OpenAICallback is registered for handling create **but there are no endpoints waiting to receive the result**.
Run of <lambda> in <Thread(TP.submit with debug timeout_1, started 7936)> failed with: Could not locate app.retrieve.args.query in app/record.

**Comment by gjke** [comment]
I am having the same issue. How did you resolve it?

**Comment by kmr666** [comment]
> I am having the same issue. How did you resolve it?

I have encountered the same situation, do you have a solution？

**Comment by sfc-gh-jreini** [comment]
When using the AzureOpenAI provider, you need to set the following as environmental variables rather than passing them to the provider. 

- AZURE_OPENAI_ENDPOINT
- AZURE_OPENAI_API_KEY
- OPENAI_API_VERSION

Then you just need to pass the deployment name only to the provider:

```python
from trulens_eval.feedback.provider.openai import AzureOpenAI
openai_provider = AzureOpenAI(deployment_name="...")

openai_provider.relevance(
    prompt="Where is Germany?",
    response="Poland is in Europe."
) # low relevance
```

You can see the API reference here: https://www.trulens.org/trulens_eval/api/provider/openai/azureopenai/#trulens_eval.feedback.provider.openai.AzureOpenAI

**Comment by kmr666** [comment]
> When using the AzureOpenAI provider, you need to set the following as environmental variables rather than passing them to the provider.
> 
> * AZURE_OPENAI_ENDPOINT
> * AZURE_OPENAI_API_KEY
> * OPENAI_API_VERSION
> 
> Then you just need to pass the deployment name only to the provider:
> 
> ```python
> from trulens_eval.feedback.provider.openai import AzureOpenAI
> openai_provider = AzureOpenAI(deployment_name="...")
> 
> openai_provider.relevance(
>     prompt="Where is Germany?",
>     response="Poland is in Europe."
> ) # low relevance
> ```
> 
> You can see the API reference here: https://www.trulens.org/trulens_eval/api/provider/openai/azureopenai/#trulens_eval.feedback.provider.openai.AzureOpenAI

This method is effective, thank you very much for your help.
