### ISSUE TITLE
Private LLM

### ISSUE THREAD

**Issue by alexandruvesa** [truera/trulens#736]
Can we use Trulens also with a private LLM? For example, all my models are running on AWS EC2. Can I run there trulens to evaluate my models?

Thanks

**Comment by joshreini1** [comment]
@alexandruvesa - are you wanting to use your private LLM for evaluation? Or simply to evaluate an app that uses a private LLM?

**Comment by alexandruvesa** [comment]
Evaluate an app that uses a private LLM @joshreini1 .

**Comment by joshreini1** [comment]
Any regular TruLens usage should work in an ec2. Feel free to share more details about your specific scenario

**Comment by avinashmaheshjoshi** [comment]
Closing this ticket. Please re-open if you have further questions.
