### ISSUE TITLE
Custom Feedback Provider

### ISSUE THREAD

**Issue by htcml** [truera/trulens#773]
Suppose I have an endpoint set up for Mistral 7B model. How to create a custom feedback provider which utilizes this endpoint/model?

**Comment by joshreini1** [comment]
Hey @htcml !

You can write a custom feedback function with any arbitrary callable: [DOCS](https://www.trulens.org/trulens_eval/custom_feedback_functions/)

If your endpoint is compatible with LangChain, you could also use our LangChain provider: [DOCS](https://www.trulens.org/trulens_eval/api/langchain_provider/)

**Comment by HannaHUp** [comment]
> Hey @htcml !
> 
> You can write a custom feedback function with any arbitrary callable: [DOCS](https://www.trulens.org/trulens_eval/custom_feedback_functions/)
> 
> If your endpoint is compatible with LangChain, you could also use our LangChain provider: [DOCS](https://www.trulens.org/trulens_eval/api/langchain_provider/)

404 - Not found
