### ISSUE TITLE
Arbitrary LLM endpoint as Provider 

### ISSUE THREAD

**Issue by lalehsg** [truera/trulens#789]
Hi! I am wondering if it is possible to use a self-deployed LLM endpoint as the provider of the Trulens feedback. I checked the code briefly and noticed that LiteLLM, google_vertex, bedrock, huggingface, open ai, and Azure open ai are supported. I have tried  the Azure open ai and integration was seamless. However, I am curious about possibility of programmatically connecting to arbitrary model endpoint via http/curl requests. I'd appreciate your help and thoughts on this.

**Comment by joshreini1** [comment]
@lalehsg can you use the langchain provider for this?

**Comment by yuvneshtruera** [comment]
@lalehsg Please let us know if this works for you?

**Comment by yuvneshtruera** [comment]
Closing this for now. Please let us know if this needs reopening

**Comment by lalehsg** [comment]
hi sorry for the delay. thanks for the reply. the doc link you provided doesn't work. but i think i get the solution. using langchain wrapper functions for this purpose...
