### ISSUE TITLE
Add docs for running evals on pre-logged data

### ISSUE THREAD

**Issue by joshreini1** [truera/trulens#800]

**Comment by Niharika6442** [comment]
+1 Could you add docs for already existing OpenAI results evaluation instead of retrieving through LlamaIndex?

**Comment by joshreini1** [comment]
> +1 Could you add docs for already existing OpenAI results evaluation instead of retrieving through LlamaIndex?

Can you clarify further on what you mean by "already existing results avluation"? @Niharika6442

**Comment by joshreini1** [comment]
Coming soon!

**Comment by joshreini1** [comment]
Done! See: https://www.trulens.org/trulens_eval/feedback_functions_existing_data/

**Comment by Niharika6442** [comment]
Can you provide an example notebook as a quickstart?

**Comment by prasad4fun** [comment]
> Where is the retriever_component defined for below line? context_call = retriever_component.get_context
> 
> Also, Can you provide an example notebook as a quickstart?

@joshreini1, could you please explain "context_call = retriever_component.get_context". In cases where already a dataframe of questions, answers and retrieved contexts are available, do we still need to pass the selector for a presumed context retrieval component's call?

**Comment by Niharika6442** [comment]
@joshreini1 anything on this?

**Comment by joshreini1** [comment]
@prasad4fun the context_call definition is used to record the structure of your application. If you need to include a context as an intermediate step of your app - I'd recommend setting the context selector here and record the `context_call` `args` and `rets` like shown in the docs.

There's also a notebook that goes a bit deeper on these things here: [Virtual Example](https://github.com/truera/trulens/blob/main/trulens_eval/examples/experimental/virtual_example.ipynb)

**Comment by joshreini1** [comment]
Will put together more of a "quickstart" on this at some point soon

**Comment by shrijayan** [comment]
https://www.trulens.org/trulens_eval/evaluation/running_feedback_functions/existing_data/#:~:text=In%20many%20cases%2C%20developers%20have,data%2C%20independent%20of%20the%20recorder%20.
