### ISSUE TITLE
Contradicting results: Getting NaN in the notebook but actual value shows in the Streamlit app

### ISSUE THREAD

**Issue by magedhelmy1** [truera/trulens#808]
I am following the deeplearning.ai course in [Building and Evaluating Advanced RAG - part 3, Rag Triad of metrics](https://learn.deeplearning.ai/building-evaluating-advanced-rag/lesson/3/rag-triad-of-metrics).

When I execute

```
import pandas as pd

pd.set_option("display.max_colwidth", None)
records[["input", "output"] + feedback]
```

I get the below with alot of NaN values:

![Screenshot 2024-01-20 at 21 45 41](https://github.com/truera/trulens/assets/63347261/20cd69fa-e94a-4a0c-b819-9d4ff45204d2)

When I get the equivalent question in the Streamlit app, it actually has the values.

<img width="947" alt="Screenshot 2024-01-20 at 21 48 49" src="https://github.com/truera/trulens/assets/63347261/a5e321a3-e823-486c-ba68-4b358d4c16b1">

**Comment by joshreini1** [comment]
Seems likely that the feedback scores were not yet available when you created the records df. Please rerun, expect you will see the same values as in streamlit
