### ISSUE TITLE
Groundedness has incorrect values

### ISSUE THREAD

**Issue by magedhelmy1** [truera/trulens#809]
In the Groundedness we see =0.5, but actualy results are 0.5 and 0.0, shouldnt it be 0.25?
If we look at the Context relevance it took the average instead of the highest

<img width="989" alt="Screenshot 2024-01-20 at 21 55 47" src="https://github.com/truera/trulens/assets/63347261/2d621cb9-6d5c-4e32-b9e9-a629e437f18b">

In another cases, the Groundedness seems to have a random value

<img width="1041" alt="Screenshot 2024-01-20 at 21 56 54" src="https://github.com/truera/trulens/assets/63347261/3ab348a3-c3e7-480c-8d85-30becf5aa790">

**Comment by yuvneshtruera** [comment]
Thank you for bringing this to our attention, we are looking at this.

**Comment by joshreini1** [comment]
@magedhelmy1 - can you please share how you defined the groundedness feedback functions?

**Comment by joshreini1** [comment]
Thanks @magedhelmy1 ! Can you retry with TruLens installed from GitHub? This issue may be fixed in main

**Comment by joshreini1** [comment]
@magedhelmy1 please adjust your groundedness definition to:

```
groundedness = (
        Feedback(grounded.groundedness_measure_with_cot_reasons, name="Groundedness")
            .on(TruLlama.select_source_nodes().node.text.collect())
            .on_output()
            .aggregate(grounded.grounded_statements_aggregator)
    )
```
