### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by budhewarvijay0407** [truera/trulens#810]
Im getting this error whenever Im running tru.run_dashboard() : 

ileNotFoundError                         Traceback (most recent call last)
Cell In[42], line 1
----> 1 tru.run_dashboard()

File C:\anaconda_setup\envs\sdg_goal_tl\lib\site-packages\trulens_eval\tru.py:572, in Tru.run_dashboard(self, port, address, force, _dev)
    565     args.append(f"--server.address={address}")
    567 args += [
    568     leaderboard_path, "--", "--database-url",
    569     self.db.engine.url.render_as_string(hide_password=False)
    570 ]
--> 572 proc = subprocess.Popen(
    573     args,
    574     stdout=subprocess.PIPE,
    575     stderr=subprocess.PIPE,
    576     text=True,
    577     **env_opts
    578 )
    580 started = threading.Event()
    581 tunnel_started = threading.Event()

File C:\anaconda_setup\envs\sdg_goal_tl\lib\subprocess.py:951, in Popen.__init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, user, group, extra_groups, encoding, errors, text, umask)
    947         if self.text_mode:
    948             self.stderr = io.TextIOWrapper(self.stderr,
    949                     encoding=encoding, errors=errors)
--> 951     self._execute_child(args, executable, preexec_fn, close_fds,
    952                         pass_fds, cwd, env,
    953                         startupinfo, creationflags, shell,
    954                         p2cread, p2cwrite,
    955                         c2pread, c2pwrite,
    956                         errread, errwrite,
    957                         restore_signals,
    958                         gid, gids, uid, umask,
    959                         start_new_session)
    960 except:
    961     # Cleanup if the child failed starting.
    962     for f in filter(None, (self.stdin, self.stdout, self.stderr)):

File C:\anaconda_setup\envs\sdg_goal_tl\lib\subprocess.py:1436, in Popen._execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_gid, unused_gids, unused_uid, unused_umask, unused_start_new_session)
   1434 # Start the process
   1435 try:
-> 1436     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
   1437                              # no special security
   1438                              None, None,
   1439                              int(not close_fds),
   1440                              creationflags,
   1441                              env,
   1442                              cwd,
   1443                              startupinfo)
   1444 finally:
   1445     # Child is launched. Close the parent's copy of those pipe
   1446     # handles that only the child should have open.  You need
   (...)
   1449     # pipe will not close when the child process exits and the
   1450     # ReadFile will hang.
   1451     self._close_pipe_fds(p2cread, p2cwrite,
   1452                          c2pread, c2pwrite,
   1453                          errread, errwrite)

FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by julfr** [comment]
@budhewarvijay0407 How did you solve your problem?

**Comment by budhewarvijay0407** [comment]
Please upgrade the streamlit
