### ISSUE TITLE
Summary with CoT Feedback function doesn't capture cost for Bedrock models and the reason for the score given

### ISSUE THREAD

**Issue by SanjuMLGeek** [truera/trulens#811]
Hello,

I have implemented Summary of CoT feedback as below. The Dashboard shows it didn't capture the cost for Bedrock based model as well as the record level activity shows no "reason" for the score. In my case one record shows the score as "1" but I don't feel the summary covered all facts while other record shows "0.5" and I can't differentiate the reasoning.

Appreciate your help and attention.

`from trulens_eval import Bedrock as TBedrock
from trulens_eval.feedback.provider.base import Provider, LLMProvider
from trulens_eval.feedback.provider.bedrock import Bedrock as fBedrock
from trulens_eval.tru_custom_app import instrument

import numpy as np

tru = Tru()
ftitan = fBedrock()

f_summary_with_cot = (
    Feedback(ftitan.summary_with_cot_reasons, name = "SummaryCoT")
    .on_input_output()
)

llm = Bedrock(model_id="anthropic.claude-instant-v1")

PROMPT = PromptTemplate(
    template=prompt_template, input_variables=["context"]
)

chain = LLMChain(
    llm=llm,
    prompt=PROMPT,
    verbose=False
)
    
tru_recorder = tru.Chain(
    chain,
    app_id='Claim_Summary_Prompt2',
    feedbacks=[f_summary_with_cot]
)`

Here is the screenshot:

<img width="1324" alt="image" src="https://github.com/truera/trulens/assets/43816307/92782f48-da68-469d-8be0-8ef9d52ed93e">

<img width="785" alt="image" src="https://github.com/truera/trulens/assets/43816307/2804b4ae-559f-4dfe-9e54-342da26aac96">

<img width="785" alt="image" src="https://github.com/truera/trulens/assets/43816307/9262813a-7fe8-4507-85d5-57aa35d111c8">

**Comment by joshreini1** [comment]
Thanks @SanjuMLGeek - looking into this

**Comment by joshreini1** [comment]
Hey @SanjuMLGeek ! We made big improvements to the summarization feedback (now named comprehensiveness) and these changes are now released in 0.23.0. Please give it a shot!
