### ISSUE TITLE
Groundedness metric surpasses the defined limit

### ISSUE THREAD

**Issue by kouskouss** [truera/trulens#814]
I implemented the use case from this notebook of trulens: [Colab Link](https://colab.research.google.com/github/truera/trulens/blob/main/trulens_eval/examples/quickstart/quickstart.ipynb), but for a list of 500 consecutive queries, the computed Groundedness is 7.259001e+09. Conversely, when using the exact same code for a list of 100 queries, the Groundedness falls within the expected limits (0 to 1). What could be the potential issue in the case of 500 queries?

**Comment by joshreini1** [comment]
Hi @kouskouss - it's likely the issue here is the LLM performing the evaluations. We've done some refactoring for groundedness that may help with this.

Can you install from github and retry?

Please let me know if this issue persists.

**Comment by Bartosz-Lewandowski** [comment]
With new version from github it throws validation error and final groundedness is calculated properly!
But with this version total_tokens is not calculated correctly, it always returns 0

**Comment by kouskouss** [comment]
Hi @joshreini1, I tried your suggestion and now it works! Thank you.

**Comment by joshreini1** [comment]
Great news!

@Bartosz-Lewandowski - if you are seeing issues with the token tracking, please open a new issue including the provider/model you are using. Thanks
