### ISSUE TITLE
Using a Open-Source LLM as Provider

### ISSUE THREAD

**Issue by maurovitaleBH** [truera/trulens#819]
I'm trying to use an open-source LLM (models available on huggingface) as a Provider, locally running, instead to use OpenAI provider. Is it possible?

**Comment by brarrow** [comment]
For example: https://github.com/truera/trulens/blob/main/trulens_eval/examples/expositional/models/alpaca7b_local_llm.ipynb

**Comment by brarrow** [comment]
Yes, for example: https://github.com/truera/trulens/blob/main/trulens_eval/examples/expositional/models/ollama_quickstart.ipynb
