### ISSUE TITLE
Errors due do not exctly matching strings in LLMprovider class

### ISSUE THREAD

**Issue by munila** [truera/trulens#825]
In line 157 of the base.py file in the providerst folder (https://github.com/truera/trulens/blob/9eb94ad34bf8b1f27a715fa898336c171a51e54b/trulens_eval/trulens_eval/feedback/provider/base.py#L157) the line.index command does not use the exact same string as the if statement in L155/L144 (One has a ":", one doesnt). I try to use a local huggingface llm pipeline with llama_index and when trying to apply a feedbackfunction ("relevance_with_cot_reasoning") it crashes at this point with the error "ValueError: substring not found". 
Not sure if thats the only cause for that error but I think using the same string for the index command and the if statement will avoid possible unwanted behavior.

**Comment by joshreini1** [comment]
@munila - thanks! This was resolved in trulens_eval==0.23.0
