### ISSUE TITLE
TruLens with custom hosted model on SageMaker

### ISSUE THREAD

**Issue by abdulhaseeb-nbs** [truera/trulens#828]
Is there a way that we can use custom hosted model on Sagemaker to calculate all the evaluation scores?

This is not an issue, this is for information.

**Comment by joshreini1** [comment]
Thanks for the question @abdulhaseeb-nbs !

You can create a custom feedback function that uses any custom model. See related docs: https://www.trulens.org/trulens_eval/custom_feedback_functions/

However you would need to recreate the prompting for out-of-the-box evals. We don't currently have a way to run an arbitrary/custom provider with existing feedback implementations
