### ISSUE TITLE
Facing Issue: Using an Custom OpenAI Gateway with trulens

### ISSUE THREAD

**Issue by krishmurarka** [truera/trulens#844]
So in trulens we are having and OpenAI Object , which requires the api-key and stuff of Open AI.
from trulens_eval.feedback.provider.openai import OpenAI

But , if I want to send the request to my custom AI_Gateway, which is using a seperate AI model. How to use that with truelens?

**Comment by joshreini1** [comment]
Hey @krishmurarka 

Can you do this with our langchain provider? https://www.trulens.org/trulens_eval/api/langchain_provider/

Basically you just need to set up your AI_Gateway as a chain, and then pass it to the TruLens LangChain provider

**Comment by joshreini1** [comment]
Hey @krish-murarka - here's the updated link: https://www.trulens.org/trulens_eval/api/provider/langchain/

We also made some fixes to our cost tracking in trulens-eval==0.24.1; would recommend upgrading if you're still on an older version

**Comment by joshreini1** [comment]
Feel free to share along your monkey-patching as well :)

**Comment by krish-murarka** [comment]
@joshreini1 Thank you, ohh we were using 0.21 version for trulens-eval let me bump the package.


And For Monkey Patching, we were using the llamaIndex Open AI object , but as it has  pydantic checks of model 


For we monkey patched this function of Open AI in llama: def _get_model_kwargs(self, **kwargs: Any) -> Dict[str, Any]:

OpenAI._get_model_kwargs = Custom_model_kwargs_custom
