### ISSUE TITLE
Additions to the Tru API for working with large databases

### ISSUE THREAD

**Issue by epinzur** [truera/trulens#848]
I've been working primarily with very large databases and I find the [Tru API](https://www.trulens.org/trulens_eval/api/tru/) to be a bit lacking. 

In particular, methods like the following would be very helpful:

- [ ] * `tru.list_records(app_id)`: Get a list of record_ids in an app.
- [ ] * `tru.get_record_and_feedback(record_id)`: Get a single record and its feedback results from the database.
- [ ] * `tru.delete_record(record_id)`: Delete a single record from the database. (Useful to remove duplicate records from an App without having to reset the database and start over)
- [x] * `tru.delete_app(app_id)`: Delete an app from the database. (without having to reset the database and start over) (Helpful when an App run didn't complete due to an exception) - done in #1061 by @arn-tru 

These methods would be helpful, but not as high priority:

- [ ] * `tru.get_incomplete_records(app_id, [feedback_function_names])`: Returns a list of record_ids where the passed feedback function names don't yet have a value. Basically a way to test if the app has a full set of data yet, and if not, return the records that need to be finished.

Finally, some paging functionality would be helpful on:

- [ ] * `tru.get_records_and_feedback(app_ids)`

**Comment by priyalorha** [comment]
https://github.com/truera/trulens/pull/939 ?
