### ISSUE TITLE
Custom LangChain Retriever is not logged

### ISSUE THREAD

**Issue by q2wxec** [truera/trulens#854]
In my Chain,I find that only LangChain Retriever can be logged,Custom Retriever is not logged.

##  LangChain Retriever 
![image](https://github.com/truera/trulens/assets/24437317/7611c1dc-e149-4142-a833-6f0aa1ff229e)
## Custom Retriever
```
class ContextExpandRetriver(BaseRetriever):
    def _get_relevant_documents(
        self,
        query: str,
        *,
        run_manager: CallbackManagerForRetrieverRun,
        **kwargs: Any,
    ) -> List[Document]:
        source_documents = []
        # do something to ContextExpandRetriver
        return source_documents
```
![image](https://github.com/truera/trulens/assets/24437317/fb37d0fc-cef4-4467-8ff6-5b44f751d403)

Just replace retriever in Example blow will reproduce the problem！
https://www.trulens.org/trulens_eval/langchain_quickstart/#load-documents

Because of the bug,the lens App.select_context returns , is not log to the db, and thus can not be dealed by the Feedback
![image](https://github.com/truera/trulens/assets/24437317/5868fd26-c842-4817-a70e-4b202435201c)

**Comment by joshreini1** [comment]
Hey @q2wxec ! Thanks for creating the issue.

I’m not quite following the issue here. Is it that the expected component is not showing in the timeline (not being logged at all), or is it just not being selected by `select_context`

**Comment by joshreini1** [comment]
@q2wxec this may be fixed by #873 - can you give it a try?

**Comment by q2wxec** [comment]
> @q2wxec this may be fixed by #873 - can you install from that branch and give it a try?

ok,i will take a shoot and reply

**Comment by q2wxec** [comment]
> @q2wxec this may be fixed by #873 - can you install from that branch and give it a try?

I think this problem has been solved.However some problem occour while open the dashbord.
## This problem solved by looking into the json
![1707534707713](https://github.com/truera/trulens/assets/24437317/7ca486ec-b756-481d-bbac-001d4484d9a2)
## dashbord problem 
![image](https://github.com/truera/trulens/assets/24437317/5df3f3f3-061b-4d5b-ba42-4c43b68026d6)

**Comment by joshreini1** [comment]
Awesome news. Re: the dashboard error, this is fixed in main (and 0.22.1) but wasn’t in this branch yet. Just pulled it in to the branch

**Comment by q2wxec** [comment]
> Awesome news. Re: the dashboard error, this is fixed in main (and 0.22.1) but wasn’t in this branch yet. Just pulled it in to the branch

thx for your effort

**Comment by joshreini1** [comment]
You’re welcome! Assuming it’s working now?

**Comment by q2wxec** [comment]
> You’re welcome! Assuming it’s working now?

yes

**Comment by joshreini1** [comment]
Will close this once it's merged
