### ISSUE TITLE
Does Trulens assume Open AI Embedding access , is there a way to use it with local Hugging face embeddings like bge-large ?

### ISSUE THREAD

**Issue by arkacisco** [truera/trulens#855]
Does Trulens assume Open AI Embedding access , is there a way to use it with local Hugging face embeddings like bge-large ?

**Comment by joshreini1** [comment]
TruLens does not assume use of any particular provider for models (embedding or LLM). We are completely agnostic to your application component choice, and have many supported options (open source and proprietary) on which to run evals (known in our docs as feedback providers)
