### ISSUE TITLE
Increase provider test coverage to other feedback providers

### ISSUE THREAD

**Issue by joshreini1** [truera/trulens#869]
`test_providers.py` currently only covers OpenAI provider. Add testing for other feedback providers.

- [ ] AzureOpenAI
- [ ] Bedrock
- [ ] LiteLLM
- [x] LangChain done in #1062 by @arn-tru 
- [X] Huggingface - done in #919 by @venkatkakoju

**Comment by kshitiz305** [comment]
@joshreini1 Do we still need some more tests for the AzureOpenAI  or will the open ai test will go with the same.

**Comment by sfc-gh-jreini** [comment]
We do still need tests on AzureOpenAI. Thanks if you're offering :)
