### ISSUE TITLE
Metadata Error

### ISSUE THREAD

**Issue by redswimmer** [truera/trulens#871]
I encountered the following error in trulens_eval 0.22.0 for records with metadata:

![image](https://github.com/truera/trulens/assets/38088099/a66ca4af-f638-4dfc-aa20-7f55397e7666)

**Comment by aaronvarghese** [comment]
@joshreini1 - Fixed the bug in PR https://github.com/truera/trulens/pull/888

**Comment by joshreini1** [comment]
Closing - the fix from @aaronvarghese is merged into main and will be available in next release
