### ISSUE TITLE
Notebook not found when using the open in Colab link in the moderation 

### ISSUE THREAD

**Issue by roschler** [truera/trulens#896]
When click on the "Open in Colab" link in the moderation example:

https://colab.research.google.com/github/truera/trulens/blob/main/trulens_eval/examples/expositional/use_cases/moderation.ipynb

I get a popup dialog that says "Notebook not found":

![image](https://github.com/truera/trulens/assets/4660487/b9a8b8c9-83ea-4e7a-bf30-e5e2129850de)

It then asked me to authorize via GitHub, which I did.  I then tried the link again but I still got that error.

**Comment by kshitiz305** [comment]
HI I would like to assist you in this

**Comment by joshreini1** [comment]
Correct link is: https://colab.research.google.com/github/truera/trulens/blob/main/trulens_eval/examples/expositional/use_cases/moderation.ipynb

Will update this in the notebook.

Thanks
