### ISSUE TITLE
Found more than one `BaseRetriever` in app

### ISSUE THREAD

**Issue by AraHema** [truera/trulens#921]
When i tried to select context from retrivalQA chain in:
    from trulens_eval.app import App
    context = App.select_context(query_engine)
 
i faced this issue 
ValueError: Found more than one `BaseRetriever` in app:
        <class 'langchain.retrievers.ensemble.EnsembleRetriever'> at retriever
        <class 'langchain_core.vectorstores.VectorStoreRetriever'> at retriever.retrievers[0]
       
Is there any alternative as i need the context to be added for the context relevance and groudnedness

**Comment by AraHema** [comment]
raise RuntimeError(
RuntimeError: Could not locate app._get_relevant_documents.rets[:].page_content in app/record.

**Comment by joshreini1** [comment]
Hey @AraHema - when you inspect the feedback display in the TruLens UI, are you seeing the expected documents being evaluated?

**Comment by yuvneshtruera** [comment]
@AraHema please let us know if you still need help with this, closing this for now.
