### ISSUE TITLE
Could not locate app.get_relevant_documents.rets[:].page_content in app/record.

### ISSUE THREAD

**Issue by AraHema** [truera/trulens#936]
during the use of this method https://github.com/truera/trulens/blob/main/trulens_eval/examples/expositional/frameworks/langchain/langchain_ensemble_retriever.ipynb

i faced this issue 

KeyError: 'Key not in dictionary: get_relevant_documents'
RuntimeError: Could not locate app.get_relevant_documents.rets[:].page_content in app/record.

**Comment by joshreini1** [comment]
Can you share the full stack trace on where you are experiencing this issue @AraHema ?

**Comment by yuvneshtruera** [comment]
@AraHema Can you please let us know if you still need help?
