### ISSUE TITLE
Evaluation metrics inference

### ISSUE THREAD

**Issue by FatemaD1577** [truera/trulens#940]
Hi,

I am using truelens to evaluate the performance of one of our chat applications. I need help in understanding the metrics being used. I am not able to understand how to interpret these metrics. For eg: The answer for my query is actually incorrect, the context relevance and groundedness parameter scores depict this to some extent but I get answer relevance as always 1. 

Can some one help me understand how to interpret these metrics or provide reference to content which explain these at a deeper level? 

Thanks in advance.

**Comment by joshreini1** [comment]
Hi @FatemaD1577 !

We have material in our docs:
[Core Concept: The RAG Triad](https://www.trulens.org/trulens_eval/core_concepts_rag_triad/)

And you may also enjoy a short course on this topic we put together with Andrew Ng and Llama-Index:
[Building and Evaluating Advanced RAG](https://www.deeplearning.ai/short-courses/building-evaluating-advanced-rag/)

**Comment by FatemaD1577** [comment]
Thank you!! @joshreini1 for the prompt reply. Will check the course.

**Comment by joshreini1** [comment]
You're welcome!
