### ISSUE TITLE
[FEAT]  Adding support of base feedback functions to different languages

### ISSUE THREAD

**Issue by sruap1214** [truera/trulens#943]
**Feature Description**
Hi. I would like to know what would be the best way to implement the same feedback functions that you have with the prompt in different languages?

**Reason**
It is needed because after running some test, the score can be very similar if a change the prompt to the other language, but the justification is a mix of different languages. 

**Importance of Feature**
Since this feedback functions some of them depends on language itself, it would nice if there would be a way in which it would easy as just change a parameter to change the language of the prompt, without needing to create a entire feedback function.

**Comment by joshreini1** [comment]
Hey @sruap1214 - it's probably best here to extend one of our existing providers to a new "custom" feedback function, but then refer to the prompts of the original feedback function as needed.

Here's the docs on extending an existing provider: https://www.trulens.org/trulens_eval/evaluation/feedback_implementations/custom_feedback_functions/#extending-existing-providers
