### ISSUE TITLE
how can I use LLM from huggingface as the provider of the Trulens feedback? 

### ISSUE THREAD

**Issue by rushmj** [truera/trulens#951]
I want to use local model that download from huggingface as the provider of the Trulens feedback for RAG Evaluation of Llama-Index project.How to set it and custom prompt?
Thank you.

**Comment by avinashmaheshjoshi** [comment]
We don't have this support right now. We can add this to our backlog as a feature request.

**Comment by shayaks** [comment]
@rushmj You can choose to write a custom feedback function as described here: https://www.trulens.org/trulens_eval/evaluation/feedback_implementations/custom_feedback_functions/

You could also extend the base Provider class to create a new provider.

**Comment by rushmj** [comment]
thanks！
