### ISSUE TITLE
[FEAT] Change database configuration

### ISSUE THREAD

**Issue by adrycerdeiro** [truera/trulens#955]
**Feature Description**
We are trying to implement Trulens-eval in an existing project that already uses a Postgresql database and Alembic to manage the migrations.
We have changed the database used by Trulens but, when we start the application, it runs [some checks](https://github.com/truera/trulens/blob/8826a03cb7881f690cd54c438ff844a6d229a89c/trulens_eval/trulens_eval/database/sqlalchemy_db.py#L54) to detect the status of the migrations applied to the database and, as we are already using Alembic with the default configuration, it tries to read the revision from the `alembic_version` table and compare it to the last revision in Trulens migrations, which make it fail.
We tried to change the Alembic configuration used by Trulens so we could change the revision table name but we don't see any option to do it.

**Reason**
 It would be great if Trulens allowed us to change these database/migrations configurations so we could use it in the same database that the application uses right now.

As a quick fix, we try to apply some monkey patching to some classes, for example, [adding the `version_table` param to the migrations file](https://github.com/truera/trulens/blob/8826a03cb7881f690cd54c438ff844a6d229a89c/trulens_eval/trulens_eval/database/migrations/env.py#L41). It almost works but the dashboard doesn't run (as it runs in a subprocess, I think that it is not able to read the patch applied and uses the default implementation).

**Importance of Feature**
We could have the Trulens feedback data in the same database where we have the application data, which allows us to create some reports about the performance of the application.
Also, we don't need to create a new database to store this information (with the maintenance associated).

**Comment by piotrm0** [comment]
Hi; I'm prototyping various ways in which we can let this be configurable. Let us know if you have any suggestions.

**Comment by adrycerdeiro** [comment]
This issue is still relevant to the latest version

**Comment by piotrm0** [comment]
Hi @adrycerdeiro , can you check out this PR: https://github.com/truera/trulens/pull/971 . It adds a table prefix option and changes the default to "trulens_" which should make it not interfere with existing alembic-managed tables.

**Comment by adrycerdeiro** [comment]
Hi @piotrm0, I'm not a Python expert (I just started to use it about 5 months ago) but the PR changes look good to me! Thanks for your work 🙏🏻
