### ISSUE TITLE
When Custom retriever and  query engine with llamaindex,get ERROR

### ISSUE THREAD

**Issue by rushmj** [truera/trulens#979]
Hello
In llamaindex,I use "BaseRetriever" and "CustomQueryEngine" class to custom Retriever with Neo4j query and use it to custom the query engine,then I put the custom_query_engine variable to "context = App.select_context(custom_query_engine)" 
I get ERROR:"Could not determine context from unrecognized `app` type {type(app)}."
it seem it only support the QueryEngine from official llamaindex package.
How can I do to make my customQueryEngine work? 
Thank you.

**Comment by joshreini1** [comment]
Hey @rushmj can you select the context more manually with a feedback selector? Not sure `select_context` helper will work in this case.

If you're creating the new custom classes youself, I'd recommend using our custom app instrumentation with the `@instrument` decorator. This will give you easy access to the args and return of any method you tag with that decorator for evals. For an example, see the base quickstart: https://www.trulens.org/trulens_eval/getting_started/quickstarts/quickstart/
