### ISSUE TITLE
[BUG] Some docs broken / 404?

### ISSUE THREAD

**Issue by meissnereric** [truera/trulens#986]
**Bug Description**
Hey when browsing your docs I get 404 errors for https://www.trulens.org/install/,  https://www.trulens.org/trulens_eval/core_concepts/feedback_functions/ and https://www.trulens.org/trulens_eval/core_concepts/honest_harmless_helpful_evals/. I got there from the standard github docs link the top of the repo.

Same result in chrome and firefox from my desktop.

Example image:
![image](https://github.com/truera/trulens/assets/6857699/7ffebad9-a00d-4eab-b7bb-a1aab9d96a37)

I can read the docs fine using https://www.trulens.org/trulens_eval/getting_started/ and browsing from there but I think your links are messed up/outdated on the github side.

**Comment by piotrm0** [comment]
Thanks for noticing. Looks like `getting_started` was not added to these paths after a recent docs folder reorganization. Will fix shortly.

**Comment by piotrm0** [comment]
Links updated.
